/*
 * Copyright 2026 NXP
 * All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _CLOCK_CONFIG_H_
#define _CLOCK_CONFIG_H_

#include "fsl_common.h"

typedef enum {
    kClockModule_ADCClk,
    kClockModule_VBAT,
    kClockModule_CLKOUT,
    kClockModule_CLK1M,
    kClockModule_CLK48M,
    kClockModule_SOSC,
    kClockModule_CMP0Clk,
    kClockModule_SystemClk,
    kClockModule_CTIMER0Clk,
    kClockModule_CTIMER1Clk,
    kClockModule_FREQME,
    kClockModule_SIRC,
    kClockModule_FIRC,
    kClockModule_LPI2C0Clk,
    kClockModule_LPSPI0Clk,
    kClockModule_LPTMR0Clk,
    kClockModule_LPUART0Clk,
    kClockModule_LPUART1Clk,
    kClockModule_LPUART2Clk,
    kClockModule_LPUART3Clk,
    kClockModule_SYSTICKClk,
    kClockModule_SlowClk,
    kClockModule_TRACEClk,
    kClockModule_WWDT0Clk,
    kClockModule_WWDT1Clk,
} clock_module_t;

/*******************************************************************************
 * Definitions
 ******************************************************************************/

/*******************************************************************************
 ************************ BOARD_InitBootClocks function ************************
 ******************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus*/

/*!
 * @brief This function executes default configuration of clocks.
 *
 */
void BOARD_InitBootClocks(void);

#if defined(__cplusplus)
}
#endif /* __cplusplus*/

/*******************************************************************************
 ******************** Configuration BOARD_BootClockFRO12M **********************
 ******************************************************************************/
/*******************************************************************************
 * Definitions for BOARD_BootClockFRO12M configuration
 ******************************************************************************/
#define BOARD_BOOTCLOCKFRO12M_CORE_CLOCK           12000000U  /*!< Core clock frequency: 12000000Hz */

/* Clock outputs (values are in Hz): */
#define BOARD_BOOTCLOCKFRO12M_ADC_CLOCK               0UL            /* Clock consumers of ADC_clock output : ADC0 */
#define BOARD_BOOTCLOCKFRO12M_CLK16K_0_CLOCK          0UL            /* Clock consumers of CLK16K_0_clock output : CMP0, LPTMR0, WUU0 */
#define BOARD_BOOTCLOCKFRO12M_CLK16K_1_CLOCK          0UL            /* Clock consumers of CLK16K_1_clock output : N/A */
#define BOARD_BOOTCLOCKFRO12M_CLK32K_0_CLOCK          0UL            /* Clock consumers of CLK32K_0_clock output : N/A */
#define BOARD_BOOTCLOCKFRO12M_CLK32K_1_CLOCK          0UL            /* Clock consumers of CLK32K_1_clock output : N/A */
#define BOARD_BOOTCLOCKFRO12M_CLKOUT_CLOCK            0UL            /* Clock consumers of CLKOUT_clock output : N/A */
#define BOARD_BOOTCLOCKFRO12M_CLK_1M_CLOCK            1000000UL      /* Clock consumers of CLK_1M_clock output : CMC */
#define BOARD_BOOTCLOCKFRO12M_CLK_48M_CLOCK           48000000UL     /* Clock consumers of CLK_48M_clock output : N/A */
#define BOARD_BOOTCLOCKFRO12M_CLK_IN_CLOCK            0UL            /* Clock consumers of CLK_IN_clock output : N/A */
#define BOARD_BOOTCLOCKFRO12M_CMP0_FUNC_DIV_CLOCK     0UL            /* Clock consumers of CMP0_FUNC_DIV_clock output : CMP0 */
#define BOARD_BOOTCLOCKFRO12M_CMP0_RR_DIV_CLOCK       0UL            /* Clock consumers of CMP0_RR_DIV_clock output : CMP0 */
#define BOARD_BOOTCLOCKFRO12M_CPU_CLOCK               12000000UL     /* Clock consumers of CPU_clock output : N/A */
#define BOARD_BOOTCLOCKFRO12M_CTIMER0_CLOCK           0UL            /* Clock consumers of CTIMER0_clock output : CTIMER0 */
#define BOARD_BOOTCLOCKFRO12M_CTIMER1_CLOCK           0UL            /* Clock consumers of CTIMER1_clock output : CTIMER1 */
#define BOARD_BOOTCLOCKFRO12M_FREQME_REFERENCE_CLOCK  12000000UL     /* Clock consumers of FREQME_reference_clock output : N/A */
#define BOARD_BOOTCLOCKFRO12M_FREQME_TARGET_CLOCK     12000000UL     /* Clock consumers of FREQME_target_clock output : N/A */
#define BOARD_BOOTCLOCKFRO12M_FRO_12M_DIV_CLOCK       12000000UL     /* Clock consumers of FRO_12M_DIV_clock output : N/A */
#define BOARD_BOOTCLOCKFRO12M_FRO_12M_CLOCK           12000000UL     /* Clock consumers of FRO_12M_clock output : N/A */
#define BOARD_BOOTCLOCKFRO12M_FRO_HF_DIV_CLOCK        72000000UL     /* Clock consumers of FRO_HF_DIV_clock output : N/A */
#define BOARD_BOOTCLOCKFRO12M_FRO_HF_CLOCK            72000000UL     /* Clock consumers of FRO_HF_clock output : N/A */
#define BOARD_BOOTCLOCKFRO12M_LPI2C0_CLOCK            0UL            /* Clock consumers of LPI2C0_clock output : LPI2C0 */
#define BOARD_BOOTCLOCKFRO12M_LPSPI0_CLOCK            0UL            /* Clock consumers of LPSPI0_clock output : LPSPI0 */
#define BOARD_BOOTCLOCKFRO12M_LPTMR0_CLOCK            0UL            /* Clock consumers of LPTMR0_clock output : LPTMR0 */
#define BOARD_BOOTCLOCKFRO12M_LPUART0_CLOCK           0UL            /* Clock consumers of LPUART0_clock output : LPUART0 */
#define BOARD_BOOTCLOCKFRO12M_LPUART1_CLOCK           0UL            /* Clock consumers of LPUART1_clock output : LPUART1 */
#define BOARD_BOOTCLOCKFRO12M_LPUART2_CLOCK           0UL            /* Clock consumers of LPUART2_clock output : LPUART2 */
#define BOARD_BOOTCLOCKFRO12M_LPUART3_CLOCK           0UL            /* Clock consumers of LPUART3_clock output : LPUART3 */
#define BOARD_BOOTCLOCKFRO12M_MAIN_CLOCK              12000000UL     /* Clock consumers of MAIN_clock output : FLEXPWM0 */
#define BOARD_BOOTCLOCKFRO12M_SYSTICK_CLOCK           0UL            /* Clock consumers of SYSTICK_clock output : SysTick */
#define BOARD_BOOTCLOCKFRO12M_SLOW_CLOCK              3000000UL      /* Clock consumers of Slow_clock output : CMC, LPTMR0, TRNG0, WUU0 */
#define BOARD_BOOTCLOCKFRO12M_SYSTEM_CLOCK            12000000UL     /* Clock consumers of System_clock output : ADC0, CMP0, CTIMER0, CTIMER1, DMA0, FLEXPWM0, FREQME0, GPIO0, GPIO1, GPIO2, GPIO3, LPI2C0, LPSPI0, LPUART0, LPUART1, LPUART2, LPUART3, OPAMP0, PORT0, PORT1, PORT2, PORT3, SWD, SysTick, WWDT0, WWDT1 */
#define BOARD_BOOTCLOCKFRO12M_TRACE_CLOCK             12000000UL     /* Clock consumers of TRACE_clock output : SWD */
#define BOARD_BOOTCLOCKFRO12M_WWDT0_CLOCK             1000000UL      /* Clock consumers of WWDT0_clock output : WWDT0 */
#define BOARD_BOOTCLOCKFRO12M_WWDT1_CLOCK             0UL            /* Clock consumers of WWDT1_clock output : WWDT1 */


/*******************************************************************************
 * API for BOARD_BootClockFRO12M configuration
 ******************************************************************************/
#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus*/

/*!
 * @brief This function contains initialization of clocks module.
 *
 */
void BOARD_BootClockFRO12M_InitClockModule(clock_module_t module);

/*!
 * @brief This function executes configuration of clocks.
 *
 */
void BOARD_BootClockFRO12M(void);

#if defined(__cplusplus)
}
#endif /* __cplusplus*/

/*******************************************************************************
 ******************* Configuration BOARD_BootClockFROHF36M *********************
 ******************************************************************************/
/*******************************************************************************
 * Definitions for BOARD_BootClockFROHF36M configuration
 ******************************************************************************/
#define BOARD_BOOTCLOCKFROHF36M_CORE_CLOCK         36000000U  /*!< Core clock frequency: 36000000Hz */

/* Clock outputs (values are in Hz): */
#define BOARD_BOOTCLOCKFROHF36M_ADC_CLOCK             0UL            /* Clock consumers of ADC_clock output : ADC0 */
#define BOARD_BOOTCLOCKFROHF36M_CLK16K_0_CLOCK        0UL            /* Clock consumers of CLK16K_0_clock output : CMP0, LPTMR0, WUU0 */
#define BOARD_BOOTCLOCKFROHF36M_CLK16K_1_CLOCK        0UL            /* Clock consumers of CLK16K_1_clock output : N/A */
#define BOARD_BOOTCLOCKFROHF36M_CLK32K_0_CLOCK        0UL            /* Clock consumers of CLK32K_0_clock output : N/A */
#define BOARD_BOOTCLOCKFROHF36M_CLK32K_1_CLOCK        0UL            /* Clock consumers of CLK32K_1_clock output : N/A */
#define BOARD_BOOTCLOCKFROHF36M_CLKOUT_CLOCK          0UL            /* Clock consumers of CLKOUT_clock output : N/A */
#define BOARD_BOOTCLOCKFROHF36M_CLK_1M_CLOCK          1000000UL      /* Clock consumers of CLK_1M_clock output : CMC */
#define BOARD_BOOTCLOCKFROHF36M_CLK_48M_CLOCK         48000000UL     /* Clock consumers of CLK_48M_clock output : N/A */
#define BOARD_BOOTCLOCKFROHF36M_CLK_IN_CLOCK          0UL            /* Clock consumers of CLK_IN_clock output : N/A */
#define BOARD_BOOTCLOCKFROHF36M_CMP0_FUNC_DIV_CLOCK   0UL            /* Clock consumers of CMP0_FUNC_DIV_clock output : CMP0 */
#define BOARD_BOOTCLOCKFROHF36M_CMP0_RR_DIV_CLOCK     0UL            /* Clock consumers of CMP0_RR_DIV_clock output : CMP0 */
#define BOARD_BOOTCLOCKFROHF36M_CPU_CLOCK             36000000UL     /* Clock consumers of CPU_clock output : N/A */
#define BOARD_BOOTCLOCKFROHF36M_CTIMER0_CLOCK         0UL            /* Clock consumers of CTIMER0_clock output : CTIMER0 */
#define BOARD_BOOTCLOCKFROHF36M_CTIMER1_CLOCK         0UL            /* Clock consumers of CTIMER1_clock output : CTIMER1 */
#define BOARD_BOOTCLOCKFROHF36M_FREQME_REFERENCE_CLOCK 12000000UL    /* Clock consumers of FREQME_reference_clock output : N/A */
#define BOARD_BOOTCLOCKFROHF36M_FREQME_TARGET_CLOCK   12000000UL     /* Clock consumers of FREQME_target_clock output : N/A */
#define BOARD_BOOTCLOCKFROHF36M_FRO_12M_DIV_CLOCK     12000000UL     /* Clock consumers of FRO_12M_DIV_clock output : N/A */
#define BOARD_BOOTCLOCKFROHF36M_FRO_12M_CLOCK         12000000UL     /* Clock consumers of FRO_12M_clock output : N/A */
#define BOARD_BOOTCLOCKFROHF36M_FRO_HF_DIV_CLOCK      36000000UL     /* Clock consumers of FRO_HF_DIV_clock output : N/A */
#define BOARD_BOOTCLOCKFROHF36M_FRO_HF_CLOCK          36000000UL     /* Clock consumers of FRO_HF_clock output : N/A */
#define BOARD_BOOTCLOCKFROHF36M_LPI2C0_CLOCK          0UL            /* Clock consumers of LPI2C0_clock output : LPI2C0 */
#define BOARD_BOOTCLOCKFROHF36M_LPSPI0_CLOCK          0UL            /* Clock consumers of LPSPI0_clock output : LPSPI0 */
#define BOARD_BOOTCLOCKFROHF36M_LPTMR0_CLOCK          0UL            /* Clock consumers of LPTMR0_clock output : LPTMR0 */
#define BOARD_BOOTCLOCKFROHF36M_LPUART0_CLOCK         0UL            /* Clock consumers of LPUART0_clock output : LPUART0 */
#define BOARD_BOOTCLOCKFROHF36M_LPUART1_CLOCK         0UL            /* Clock consumers of LPUART1_clock output : LPUART1 */
#define BOARD_BOOTCLOCKFROHF36M_LPUART2_CLOCK         0UL            /* Clock consumers of LPUART2_clock output : LPUART2 */
#define BOARD_BOOTCLOCKFROHF36M_LPUART3_CLOCK         0UL            /* Clock consumers of LPUART3_clock output : LPUART3 */
#define BOARD_BOOTCLOCKFROHF36M_MAIN_CLOCK            36000000UL     /* Clock consumers of MAIN_clock output : FLEXPWM0 */
#define BOARD_BOOTCLOCKFROHF36M_SYSTICK_CLOCK         0UL            /* Clock consumers of SYSTICK_clock output : SysTick */
#define BOARD_BOOTCLOCKFROHF36M_SLOW_CLOCK            9000000UL      /* Clock consumers of Slow_clock output : CMC, LPTMR0, TRNG0, WUU0 */
#define BOARD_BOOTCLOCKFROHF36M_SYSTEM_CLOCK          36000000UL     /* Clock consumers of System_clock output : ADC0, CMP0, CTIMER0, CTIMER1, DMA0, FLEXPWM0, FREQME0, GPIO0, GPIO1, GPIO2, GPIO3, LPI2C0, LPSPI0, LPUART0, LPUART1, LPUART2, LPUART3, OPAMP0, PORT0, PORT1, PORT2, PORT3, SWD, SysTick, WWDT0, WWDT1 */
#define BOARD_BOOTCLOCKFROHF36M_TRACE_CLOCK           36000000UL     /* Clock consumers of TRACE_clock output : SWD */
#define BOARD_BOOTCLOCKFROHF36M_WWDT0_CLOCK           1000000UL      /* Clock consumers of WWDT0_clock output : WWDT0 */
#define BOARD_BOOTCLOCKFROHF36M_WWDT1_CLOCK           0UL            /* Clock consumers of WWDT1_clock output : WWDT1 */


/*******************************************************************************
 * API for BOARD_BootClockFROHF36M configuration
 ******************************************************************************/
#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus*/

/*!
 * @brief This function contains initialization of clocks module.
 *
 */
void BOARD_BootClockFROHF36M_InitClockModule(clock_module_t module);

/*!
 * @brief This function executes configuration of clocks.
 *
 */
void BOARD_BootClockFROHF36M(void);

#if defined(__cplusplus)
}
#endif /* __cplusplus*/

/*******************************************************************************
 ******************* Configuration BOARD_BootClockFROHF72M *********************
 ******************************************************************************/
/*******************************************************************************
 * Definitions for BOARD_BootClockFROHF72M configuration
 ******************************************************************************/
#define BOARD_BOOTCLOCKFROHF72M_CORE_CLOCK         72000000U  /*!< Core clock frequency: 72000000Hz */

/* Clock outputs (values are in Hz): */
#define BOARD_BOOTCLOCKFROHF72M_ADC_CLOCK             0UL            /* Clock consumers of ADC_clock output : ADC0 */
#define BOARD_BOOTCLOCKFROHF72M_CLK16K_0_CLOCK        0UL            /* Clock consumers of CLK16K_0_clock output : CMP0, LPTMR0, WUU0 */
#define BOARD_BOOTCLOCKFROHF72M_CLK16K_1_CLOCK        0UL            /* Clock consumers of CLK16K_1_clock output : N/A */
#define BOARD_BOOTCLOCKFROHF72M_CLK32K_0_CLOCK        0UL            /* Clock consumers of CLK32K_0_clock output : N/A */
#define BOARD_BOOTCLOCKFROHF72M_CLK32K_1_CLOCK        0UL            /* Clock consumers of CLK32K_1_clock output : N/A */
#define BOARD_BOOTCLOCKFROHF72M_CLKOUT_CLOCK          0UL            /* Clock consumers of CLKOUT_clock output : N/A */
#define BOARD_BOOTCLOCKFROHF72M_CLK_1M_CLOCK          1000000UL      /* Clock consumers of CLK_1M_clock output : CMC */
#define BOARD_BOOTCLOCKFROHF72M_CLK_48M_CLOCK         48000000UL     /* Clock consumers of CLK_48M_clock output : N/A */
#define BOARD_BOOTCLOCKFROHF72M_CLK_IN_CLOCK          0UL            /* Clock consumers of CLK_IN_clock output : N/A */
#define BOARD_BOOTCLOCKFROHF72M_CMP0_FUNC_DIV_CLOCK   0UL            /* Clock consumers of CMP0_FUNC_DIV_clock output : CMP0 */
#define BOARD_BOOTCLOCKFROHF72M_CMP0_RR_DIV_CLOCK     0UL            /* Clock consumers of CMP0_RR_DIV_clock output : CMP0 */
#define BOARD_BOOTCLOCKFROHF72M_CPU_CLOCK             72000000UL     /* Clock consumers of CPU_clock output : N/A */
#define BOARD_BOOTCLOCKFROHF72M_CTIMER0_CLOCK         0UL            /* Clock consumers of CTIMER0_clock output : CTIMER0 */
#define BOARD_BOOTCLOCKFROHF72M_CTIMER1_CLOCK         0UL            /* Clock consumers of CTIMER1_clock output : CTIMER1 */
#define BOARD_BOOTCLOCKFROHF72M_FREQME_REFERENCE_CLOCK 12000000UL    /* Clock consumers of FREQME_reference_clock output : N/A */
#define BOARD_BOOTCLOCKFROHF72M_FREQME_TARGET_CLOCK   12000000UL     /* Clock consumers of FREQME_target_clock output : N/A */
#define BOARD_BOOTCLOCKFROHF72M_FRO_12M_DIV_CLOCK     12000000UL     /* Clock consumers of FRO_12M_DIV_clock output : N/A */
#define BOARD_BOOTCLOCKFROHF72M_FRO_12M_CLOCK         12000000UL     /* Clock consumers of FRO_12M_clock output : N/A */
#define BOARD_BOOTCLOCKFROHF72M_FRO_HF_DIV_CLOCK      72000000UL     /* Clock consumers of FRO_HF_DIV_clock output : N/A */
#define BOARD_BOOTCLOCKFROHF72M_FRO_HF_CLOCK          72000000UL     /* Clock consumers of FRO_HF_clock output : N/A */
#define BOARD_BOOTCLOCKFROHF72M_LPI2C0_CLOCK          0UL            /* Clock consumers of LPI2C0_clock output : LPI2C0 */
#define BOARD_BOOTCLOCKFROHF72M_LPSPI0_CLOCK          0UL            /* Clock consumers of LPSPI0_clock output : LPSPI0 */
#define BOARD_BOOTCLOCKFROHF72M_LPTMR0_CLOCK          0UL            /* Clock consumers of LPTMR0_clock output : LPTMR0 */
#define BOARD_BOOTCLOCKFROHF72M_LPUART0_CLOCK         0UL            /* Clock consumers of LPUART0_clock output : LPUART0 */
#define BOARD_BOOTCLOCKFROHF72M_LPUART1_CLOCK         0UL            /* Clock consumers of LPUART1_clock output : LPUART1 */
#define BOARD_BOOTCLOCKFROHF72M_LPUART2_CLOCK         0UL            /* Clock consumers of LPUART2_clock output : LPUART2 */
#define BOARD_BOOTCLOCKFROHF72M_LPUART3_CLOCK         0UL            /* Clock consumers of LPUART3_clock output : LPUART3 */
#define BOARD_BOOTCLOCKFROHF72M_MAIN_CLOCK            72000000UL     /* Clock consumers of MAIN_clock output : FLEXPWM0 */
#define BOARD_BOOTCLOCKFROHF72M_SYSTICK_CLOCK         0UL            /* Clock consumers of SYSTICK_clock output : SysTick */
#define BOARD_BOOTCLOCKFROHF72M_SLOW_CLOCK            18000000UL     /* Clock consumers of Slow_clock output : CMC, LPTMR0, TRNG0, WUU0 */
#define BOARD_BOOTCLOCKFROHF72M_SYSTEM_CLOCK          72000000UL     /* Clock consumers of System_clock output : ADC0, CMP0, CTIMER0, CTIMER1, DMA0, FLEXPWM0, FREQME0, GPIO0, GPIO1, GPIO2, GPIO3, LPI2C0, LPSPI0, LPUART0, LPUART1, LPUART2, LPUART3, OPAMP0, PORT0, PORT1, PORT2, PORT3, SWD, SysTick, WWDT0, WWDT1 */
#define BOARD_BOOTCLOCKFROHF72M_TRACE_CLOCK           72000000UL     /* Clock consumers of TRACE_clock output : SWD */
#define BOARD_BOOTCLOCKFROHF72M_WWDT0_CLOCK           1000000UL      /* Clock consumers of WWDT0_clock output : WWDT0 */
#define BOARD_BOOTCLOCKFROHF72M_WWDT1_CLOCK           0UL            /* Clock consumers of WWDT1_clock output : WWDT1 */


/*******************************************************************************
 * API for BOARD_BootClockFROHF72M configuration
 ******************************************************************************/
#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus*/

/*!
 * @brief This function contains initialization of clocks module.
 *
 */
void BOARD_BootClockFROHF72M_InitClockModule(clock_module_t module);

/*!
 * @brief This function executes configuration of clocks.
 *
 */
void BOARD_BootClockFROHF72M(void);

#if defined(__cplusplus)
}
#endif /* __cplusplus*/

#endif /* _CLOCK_CONFIG_H_ */

