/*
 * Copyright 2026 NXP
 * All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/
/*
 * How to setup clock using clock driver functions:
 *
 * 1. Setup clock sources.
 *
 * 2. Set up wait states of the flash.
 *
 * 3. Set up all dividers.
 *
 * 4. Set up all selectors to provide selected clocks.
 *
 */

/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Clocks v19.0
processor: MCXC162
package_id: MCXC162VFT
mcu_data: ksdk2_0
processor_version: 0.0.0
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

#include "fsl_clock.h"
#include "clock_config.h"

/*******************************************************************************
 * Definitions
 ******************************************************************************/

/*******************************************************************************
 * Variables
 ******************************************************************************/
/* System clock frequency. */
extern uint32_t SystemCoreClock;

/*******************************************************************************
 ************************ BOARD_InitBootClocks function ************************
 ******************************************************************************/
void BOARD_InitBootClocks(void)
{
    BOARD_BootClockFROHF72M();
}

/*******************************************************************************
 ******************** Configuration BOARD_BootClockFRO12M **********************
 ******************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!Configuration
name: BOARD_BootClockFRO12M
outputs:
- {id: CLK_1M_clock.outFreq, value: 1 MHz}
- {id: CLK_48M_clock.outFreq, value: 48 MHz}
- {id: CPU_clock.outFreq, value: 12 MHz}
- {id: FREQME_reference_clock.outFreq, value: 12 MHz}
- {id: FREQME_target_clock.outFreq, value: 12 MHz}
- {id: FRO_12M_DIV_clock.outFreq, value: 12 MHz}
- {id: FRO_12M_clock.outFreq, value: 12 MHz}
- {id: FRO_HF_DIV_clock.outFreq, value: 72 MHz}
- {id: FRO_HF_clock.outFreq, value: 72 MHz}
- {id: MAIN_clock.outFreq, value: 12 MHz}
- {id: Slow_clock.outFreq, value: 3 MHz}
- {id: System_clock.outFreq, value: 12 MHz}
- {id: TRACE_clock.outFreq, value: 12 MHz}
- {id: WWDT0_clock.outFreq, value: 1 MHz}
settings:
- {id: SCGMode, value: SIRC}
- {id: FROHFDIV_SYSCON_FROHFDIV_HALT, value: RUN}
- {id: FROLFDIV_SYSCON_FROLFDIV_HALT, value: RUN}
- {id: SCG.SCGSCS_CLKSEL.sel, value: SCG.FRO_12M_clock}
sources:
- {id: SCG.FIRC.outFreq, value: 72 MHz}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/*******************************************************************************
 * Code for BOARD_BootClockFRO12M configuration
 ******************************************************************************/
void BOARD_BootClockFRO12M_InitClockModule(clock_module_t module)
{

    switch(module) {
        case kClockModule_FIRC:
            CLOCK_SetClockDiv(kCLOCK_DivFRO_HF, 1U);       /* !< Set SYSCON.FROHFDIV divider to value 1 */
            CLOCK_SetupFROHFClocking(72000000U);               /*!< Enable FRO HF(72MHz) output */
            break;
        case kClockModule_SIRC:
            CLOCK_SetClockDiv(kCLOCK_DivFRO_LF, 1U);       /* !< Set SYSCON.FROLFDIV divider to value 1 */
            CLOCK_SetupFRO12MClocking();                /*!< Setup FRO12M clock */
            break;
        case kClockModule_SystemClk:
            CLOCK_SetClockDiv(kCLOCK_DivAHBCLK, 1U);       /* !< Set SYSCON.AHBCLKDIV divider to value 1 */
            CLOCK_AttachClk(kFRO12M_to_MAIN_CLK);/* !< Switch MAIN_CLK to kFRO12M */
            break;
        case kClockModule_ADCClk:
            CLOCK_AttachClk(kNONE_to_ADC);                 /* !< Switch ADC to  */
            break;
        case kClockModule_CLKOUT:
            CLOCK_AttachClk(kNONE_to_CLKOUT);              /* !< Switch CLKOUT to  */
            break;
        case kClockModule_CMP0Clk:
            CLOCK_AttachClk(kNONE_to_CMP0);                /* !< Switch CMP0 to  */
            break;
        case kClockModule_CTIMER0Clk:
            CLOCK_AttachClk(kNONE_to_CTIMER0);             /* !< Switch CTIMER0 to  */
            break;
        case kClockModule_CTIMER1Clk:
            CLOCK_AttachClk(kNONE_to_CTIMER1);             /* !< Switch CTIMER1 to  */
            break;
        case kClockModule_LPI2C0Clk:
            CLOCK_AttachClk(kNONE_to_LPI2C0);              /* !< Switch LPI2C0 to  */
            break;
        case kClockModule_LPSPI0Clk:
            CLOCK_AttachClk(kNONE_to_LPSPI0);              /* !< Switch LPSPI0 to  */
            break;
        case kClockModule_LPTMR0Clk:
            CLOCK_AttachClk(kNONE_to_LPTMR0);              /* !< Switch LPTMR0 to  */
            break;
        case kClockModule_LPUART0Clk:
            CLOCK_AttachClk(kNONE_to_LPUART0);             /* !< Switch LPUART0 to  */
            break;
        case kClockModule_LPUART1Clk:
            CLOCK_AttachClk(kNONE_to_LPUART1);             /* !< Switch LPUART1 to  */
            break;
        case kClockModule_LPUART2Clk:
            CLOCK_AttachClk(kNONE_to_LPUART2);             /* !< Switch LPUART2 to  */
            break;
        case kClockModule_LPUART3Clk:
            CLOCK_AttachClk(kNONE_to_LPUART3);             /* !< Switch LPUART3 to  */
            break;
        case kClockModule_SYSTICKClk:
            CLOCK_AttachClk(kNONE_to_SYSTICK);             /* !< Switch SYSTICK to  */
            break;
        case kClockModule_TRACEClk:
            CLOCK_AttachClk(kCPU_CLK_to_TRACE);            /* !< Switch TRACE to CPU_CLK */
            CLOCK_SetClockDiv(kCLOCK_DivTRACE, 1U);        /* !< Set MRCC.TRACE_CLKDIV divider to value 1 */
            break;
        case kClockModule_WWDT0Clk:
            CLOCK_SetClockDiv(kCLOCK_DivWWDT0, 1U);        /* !< Set MRCC.WWDT0_CLKDIV divider to value 1 */
            break;
        case kClockModule_FREQME:
            /* Configure FREQME clock */
            CLOCK_EnableClock(kCLOCK_InputMux);
            RESET_ReleasePeripheralReset(kINPUTMUX0_RST_SHIFT_RSTn);
            INPUTMUX0->FREQMEAS_REF = INPUTMUX_FREQMEAS_REF_INP(2);
            INPUTMUX0->FREQMEAS_TAR = INPUTMUX_FREQMEAS_TAR_INP(2);
            break;
        default:
            assert(false);
            break;
    }
}

void BOARD_BootClockFRO12M(void)
{
    uint32_t coreFreq;

    /* Get the CPU Core frequency */
    coreFreq = CLOCK_GetCoreSysClkFreq();

    /* The flow of increasing voltage and frequency */
    if (coreFreq <= BOARD_BOOTCLOCKFRO12M_CORE_CLOCK) {
        /* Configure Flash to support different voltage level and frequency */
        FMU0->FCTRL = (FMU0->FCTRL & ~((uint32_t)FMU_FCTRL_RWSC_MASK)) | (FMU_FCTRL_RWSC(0x0U));
    }
    BOARD_BootClockFRO12M_InitClockModule(kClockModule_SIRC);
    BOARD_BootClockFRO12M_InitClockModule(kClockModule_FIRC);
    BOARD_BootClockFRO12M_InitClockModule(kClockModule_SystemClk);

    /* The flow of decreasing voltage and frequency */
    if (coreFreq > BOARD_BOOTCLOCKFRO12M_CORE_CLOCK) {
        /* Configure Flash to support different voltage level and frequency */
        FMU0->FCTRL = (FMU0->FCTRL & ~((uint32_t)FMU_FCTRL_RWSC_MASK)) | (FMU_FCTRL_RWSC(0x0U));
    }

    BOARD_BootClockFRO12M_InitClockModule(kClockModule_ADCClk);
    BOARD_BootClockFRO12M_InitClockModule(kClockModule_CLKOUT);
    BOARD_BootClockFRO12M_InitClockModule(kClockModule_CMP0Clk);
    BOARD_BootClockFRO12M_InitClockModule(kClockModule_CTIMER0Clk);
    BOARD_BootClockFRO12M_InitClockModule(kClockModule_CTIMER1Clk);
    BOARD_BootClockFRO12M_InitClockModule(kClockModule_FREQME);
    BOARD_BootClockFRO12M_InitClockModule(kClockModule_LPI2C0Clk);
    BOARD_BootClockFRO12M_InitClockModule(kClockModule_LPSPI0Clk);
    BOARD_BootClockFRO12M_InitClockModule(kClockModule_LPTMR0Clk);
    BOARD_BootClockFRO12M_InitClockModule(kClockModule_LPUART0Clk);
    BOARD_BootClockFRO12M_InitClockModule(kClockModule_LPUART1Clk);
    BOARD_BootClockFRO12M_InitClockModule(kClockModule_LPUART2Clk);
    BOARD_BootClockFRO12M_InitClockModule(kClockModule_LPUART3Clk);
    BOARD_BootClockFRO12M_InitClockModule(kClockModule_SYSTICKClk);
    BOARD_BootClockFRO12M_InitClockModule(kClockModule_TRACEClk);
    BOARD_BootClockFRO12M_InitClockModule(kClockModule_WWDT0Clk);

    /* Set SystemCoreClock variable */
    SystemCoreClock = BOARD_BOOTCLOCKFRO12M_CORE_CLOCK;
}
/*******************************************************************************
 ******************* Configuration BOARD_BootClockFROHF36M *********************
 ******************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!Configuration
name: BOARD_BootClockFROHF36M
outputs:
- {id: CLK_1M_clock.outFreq, value: 1 MHz}
- {id: CLK_48M_clock.outFreq, value: 48 MHz}
- {id: CPU_clock.outFreq, value: 36 MHz}
- {id: FREQME_reference_clock.outFreq, value: 12 MHz}
- {id: FREQME_target_clock.outFreq, value: 12 MHz}
- {id: FRO_12M_DIV_clock.outFreq, value: 12 MHz}
- {id: FRO_12M_clock.outFreq, value: 12 MHz}
- {id: FRO_HF_DIV_clock.outFreq, value: 36 MHz}
- {id: FRO_HF_clock.outFreq, value: 36 MHz}
- {id: MAIN_clock.outFreq, value: 36 MHz}
- {id: Slow_clock.outFreq, value: 9 MHz}
- {id: System_clock.outFreq, value: 36 MHz}
- {id: TRACE_clock.outFreq, value: 36 MHz}
- {id: WWDT0_clock.outFreq, value: 1 MHz}
settings:
- {id: FROHFDIV_SYSCON_FROHFDIV_HALT, value: RUN}
- {id: FROLFDIV_SYSCON_FROLFDIV_HALT, value: RUN}
sources:
- {id: SCG.FIRC.outFreq, value: 36 MHz}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/*******************************************************************************
 * Code for BOARD_BootClockFROHF36M configuration
 ******************************************************************************/
void BOARD_BootClockFROHF36M_InitClockModule(clock_module_t module)
{

    switch(module) {
        case kClockModule_FIRC:
            CLOCK_SetClockDiv(kCLOCK_DivFRO_HF, 1U);       /* !< Set SYSCON.FROHFDIV divider to value 1 */
            CLOCK_SetupFROHFClocking(36000000U);               /*!< Enable FRO HF(36MHz) output */
            break;
        case kClockModule_SIRC:
            CLOCK_SetClockDiv(kCLOCK_DivFRO_LF, 1U);       /* !< Set SYSCON.FROLFDIV divider to value 1 */
            CLOCK_SetupFRO12MClocking();                /*!< Setup FRO12M clock */
            break;
        case kClockModule_SystemClk:
            CLOCK_SetClockDiv(kCLOCK_DivAHBCLK, 1U);       /* !< Set SYSCON.AHBCLKDIV divider to value 1 */
            CLOCK_AttachClk(kFRO_HF_to_MAIN_CLK);/* !< Switch MAIN_CLK to kFRO_HF */
            break;
        case kClockModule_ADCClk:
            CLOCK_AttachClk(kNONE_to_ADC);                 /* !< Switch ADC to  */
            break;
        case kClockModule_CLKOUT:
            CLOCK_AttachClk(kNONE_to_CLKOUT);              /* !< Switch CLKOUT to  */
            break;
        case kClockModule_CMP0Clk:
            CLOCK_AttachClk(kNONE_to_CMP0);                /* !< Switch CMP0 to  */
            break;
        case kClockModule_CTIMER0Clk:
            CLOCK_AttachClk(kNONE_to_CTIMER0);             /* !< Switch CTIMER0 to  */
            break;
        case kClockModule_CTIMER1Clk:
            CLOCK_AttachClk(kNONE_to_CTIMER1);             /* !< Switch CTIMER1 to  */
            break;
        case kClockModule_LPI2C0Clk:
            CLOCK_AttachClk(kNONE_to_LPI2C0);              /* !< Switch LPI2C0 to  */
            break;
        case kClockModule_LPSPI0Clk:
            CLOCK_AttachClk(kNONE_to_LPSPI0);              /* !< Switch LPSPI0 to  */
            break;
        case kClockModule_LPTMR0Clk:
            CLOCK_AttachClk(kNONE_to_LPTMR0);              /* !< Switch LPTMR0 to  */
            break;
        case kClockModule_LPUART0Clk:
            CLOCK_AttachClk(kNONE_to_LPUART0);             /* !< Switch LPUART0 to  */
            break;
        case kClockModule_LPUART1Clk:
            CLOCK_AttachClk(kNONE_to_LPUART1);             /* !< Switch LPUART1 to  */
            break;
        case kClockModule_LPUART2Clk:
            CLOCK_AttachClk(kNONE_to_LPUART2);             /* !< Switch LPUART2 to  */
            break;
        case kClockModule_LPUART3Clk:
            CLOCK_AttachClk(kNONE_to_LPUART3);             /* !< Switch LPUART3 to  */
            break;
        case kClockModule_SYSTICKClk:
            CLOCK_AttachClk(kNONE_to_SYSTICK);             /* !< Switch SYSTICK to  */
            break;
        case kClockModule_TRACEClk:
            CLOCK_AttachClk(kCPU_CLK_to_TRACE);            /* !< Switch TRACE to CPU_CLK */
            CLOCK_SetClockDiv(kCLOCK_DivTRACE, 1U);        /* !< Set MRCC.TRACE_CLKDIV divider to value 1 */
            break;
        case kClockModule_WWDT0Clk:
            CLOCK_SetClockDiv(kCLOCK_DivWWDT0, 1U);        /* !< Set MRCC.WWDT0_CLKDIV divider to value 1 */
            break;
        case kClockModule_FREQME:
            /* Configure FREQME clock */
            CLOCK_EnableClock(kCLOCK_InputMux);
            RESET_ReleasePeripheralReset(kINPUTMUX0_RST_SHIFT_RSTn);
            INPUTMUX0->FREQMEAS_REF = INPUTMUX_FREQMEAS_REF_INP(2);
            INPUTMUX0->FREQMEAS_TAR = INPUTMUX_FREQMEAS_TAR_INP(2);
            break;
        default:
            assert(false);
            break;
    }
}

void BOARD_BootClockFROHF36M(void)
{
    uint32_t coreFreq;

    /* Get the CPU Core frequency */
    coreFreq = CLOCK_GetCoreSysClkFreq();

    /* The flow of increasing voltage and frequency */
    if (coreFreq <= BOARD_BOOTCLOCKFROHF36M_CORE_CLOCK) {
        /* Configure Flash to support different voltage level and frequency */
        FMU0->FCTRL = (FMU0->FCTRL & ~((uint32_t)FMU_FCTRL_RWSC_MASK)) | (FMU_FCTRL_RWSC(0x0U));
    }
    BOARD_BootClockFROHF36M_InitClockModule(kClockModule_SIRC);
    BOARD_BootClockFROHF36M_InitClockModule(kClockModule_FIRC);
    BOARD_BootClockFROHF36M_InitClockModule(kClockModule_SystemClk);

    /* The flow of decreasing voltage and frequency */
    if (coreFreq > BOARD_BOOTCLOCKFROHF36M_CORE_CLOCK) {
        /* Configure Flash to support different voltage level and frequency */
        FMU0->FCTRL = (FMU0->FCTRL & ~((uint32_t)FMU_FCTRL_RWSC_MASK)) | (FMU_FCTRL_RWSC(0x0U));
    }

    BOARD_BootClockFROHF36M_InitClockModule(kClockModule_ADCClk);
    BOARD_BootClockFROHF36M_InitClockModule(kClockModule_CLKOUT);
    BOARD_BootClockFROHF36M_InitClockModule(kClockModule_CMP0Clk);
    BOARD_BootClockFROHF36M_InitClockModule(kClockModule_CTIMER0Clk);
    BOARD_BootClockFROHF36M_InitClockModule(kClockModule_CTIMER1Clk);
    BOARD_BootClockFROHF36M_InitClockModule(kClockModule_FREQME);
    BOARD_BootClockFROHF36M_InitClockModule(kClockModule_LPI2C0Clk);
    BOARD_BootClockFROHF36M_InitClockModule(kClockModule_LPSPI0Clk);
    BOARD_BootClockFROHF36M_InitClockModule(kClockModule_LPTMR0Clk);
    BOARD_BootClockFROHF36M_InitClockModule(kClockModule_LPUART0Clk);
    BOARD_BootClockFROHF36M_InitClockModule(kClockModule_LPUART1Clk);
    BOARD_BootClockFROHF36M_InitClockModule(kClockModule_LPUART2Clk);
    BOARD_BootClockFROHF36M_InitClockModule(kClockModule_LPUART3Clk);
    BOARD_BootClockFROHF36M_InitClockModule(kClockModule_SYSTICKClk);
    BOARD_BootClockFROHF36M_InitClockModule(kClockModule_TRACEClk);
    BOARD_BootClockFROHF36M_InitClockModule(kClockModule_WWDT0Clk);

    /* Set SystemCoreClock variable */
    SystemCoreClock = BOARD_BOOTCLOCKFROHF36M_CORE_CLOCK;
}

/*******************************************************************************
 ******************* Configuration BOARD_BootClockFROHF72M *********************
 ******************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!Configuration
name: BOARD_BootClockFROHF72M
called_from_default_init: true
outputs:
- {id: CLK_1M_clock.outFreq, value: 1 MHz}
- {id: CLK_48M_clock.outFreq, value: 48 MHz}
- {id: CPU_clock.outFreq, value: 72 MHz}
- {id: FREQME_reference_clock.outFreq, value: 12 MHz}
- {id: FREQME_target_clock.outFreq, value: 12 MHz}
- {id: FRO_12M_DIV_clock.outFreq, value: 12 MHz}
- {id: FRO_12M_clock.outFreq, value: 12 MHz}
- {id: FRO_HF_DIV_clock.outFreq, value: 72 MHz}
- {id: FRO_HF_clock.outFreq, value: 72 MHz}
- {id: MAIN_clock.outFreq, value: 72 MHz}
- {id: Slow_clock.outFreq, value: 18 MHz}
- {id: System_clock.outFreq, value: 72 MHz}
- {id: TRACE_clock.outFreq, value: 72 MHz}
- {id: WWDT0_clock.outFreq, value: 1 MHz}
settings:
- {id: FROHFDIV_SYSCON_FROHFDIV_HALT, value: RUN}
- {id: FROLFDIV_SYSCON_FROLFDIV_HALT, value: RUN}
sources:
- {id: SCG.FIRC.outFreq, value: 72 MHz}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/*******************************************************************************
 * Code for BOARD_BootClockFROHF72M configuration
 ******************************************************************************/
void BOARD_BootClockFROHF72M_InitClockModule(clock_module_t module)
{

    switch(module) {
        case kClockModule_FIRC:
            CLOCK_SetClockDiv(kCLOCK_DivFRO_HF, 1U);       /* !< Set SYSCON.FROHFDIV divider to value 1 */
            CLOCK_SetupFROHFClocking(72000000U);               /*!< Enable FRO HF(72MHz) output */
            break;
        case kClockModule_SIRC:
            CLOCK_SetClockDiv(kCLOCK_DivFRO_LF, 1U);       /* !< Set SYSCON.FROLFDIV divider to value 1 */
            CLOCK_SetupFRO12MClocking();                /*!< Setup FRO12M clock */
            break;
        case kClockModule_SystemClk:
            CLOCK_SetClockDiv(kCLOCK_DivAHBCLK, 1U);       /* !< Set SYSCON.AHBCLKDIV divider to value 1 */
            CLOCK_AttachClk(kFRO_HF_to_MAIN_CLK);/* !< Switch MAIN_CLK to kFRO_HF */
            break;
        case kClockModule_ADCClk:
            CLOCK_AttachClk(kNONE_to_ADC);                 /* !< Switch ADC to  */
            break;
        case kClockModule_CLKOUT:
            CLOCK_AttachClk(kNONE_to_CLKOUT);              /* !< Switch CLKOUT to  */
            break;
        case kClockModule_CMP0Clk:
            CLOCK_AttachClk(kNONE_to_CMP0);                /* !< Switch CMP0 to  */
            break;
        case kClockModule_CTIMER0Clk:
            CLOCK_AttachClk(kNONE_to_CTIMER0);             /* !< Switch CTIMER0 to  */
            break;
        case kClockModule_CTIMER1Clk:
            CLOCK_AttachClk(kNONE_to_CTIMER1);             /* !< Switch CTIMER1 to  */
            break;
        case kClockModule_LPI2C0Clk:
            CLOCK_AttachClk(kNONE_to_LPI2C0);              /* !< Switch LPI2C0 to  */
            break;
        case kClockModule_LPSPI0Clk:
            CLOCK_AttachClk(kNONE_to_LPSPI0);              /* !< Switch LPSPI0 to  */
            break;
        case kClockModule_LPTMR0Clk:
            CLOCK_AttachClk(kNONE_to_LPTMR0);              /* !< Switch LPTMR0 to  */
            break;
        case kClockModule_LPUART0Clk:
            CLOCK_AttachClk(kNONE_to_LPUART0);             /* !< Switch LPUART0 to  */
            break;
        case kClockModule_LPUART1Clk:
            CLOCK_AttachClk(kNONE_to_LPUART1);             /* !< Switch LPUART1 to  */
            break;
        case kClockModule_LPUART2Clk:
            CLOCK_AttachClk(kNONE_to_LPUART2);             /* !< Switch LPUART2 to  */
            break;
        case kClockModule_LPUART3Clk:
            CLOCK_AttachClk(kNONE_to_LPUART3);             /* !< Switch LPUART3 to  */
            break;
        case kClockModule_SYSTICKClk:
            CLOCK_AttachClk(kNONE_to_SYSTICK);             /* !< Switch SYSTICK to  */
            break;
        case kClockModule_TRACEClk:
            CLOCK_AttachClk(kCPU_CLK_to_TRACE);            /* !< Switch TRACE to CPU_CLK */
            CLOCK_SetClockDiv(kCLOCK_DivTRACE, 1U);        /* !< Set MRCC.TRACE_CLKDIV divider to value 1 */
            break;
        case kClockModule_WWDT0Clk:
            CLOCK_SetClockDiv(kCLOCK_DivWWDT0, 1U);        /* !< Set MRCC.WWDT0_CLKDIV divider to value 1 */
            break;
        case kClockModule_FREQME:
            /* Configure FREQME clock */
            CLOCK_EnableClock(kCLOCK_InputMux);
            RESET_ReleasePeripheralReset(kINPUTMUX0_RST_SHIFT_RSTn);
            INPUTMUX0->FREQMEAS_REF = INPUTMUX_FREQMEAS_REF_INP(2);
            INPUTMUX0->FREQMEAS_TAR = INPUTMUX_FREQMEAS_TAR_INP(2);
            break;
        default:
            assert(false);
            break;
    }
}

void BOARD_BootClockFROHF72M(void)
{
    uint32_t coreFreq;

    /* Get the CPU Core frequency */
    coreFreq = CLOCK_GetCoreSysClkFreq();

    /* The flow of increasing voltage and frequency */
    if (coreFreq <= BOARD_BOOTCLOCKFROHF72M_CORE_CLOCK) {
        /* Configure Flash to support different voltage level and frequency */
        FMU0->FCTRL = (FMU0->FCTRL & ~((uint32_t)FMU_FCTRL_RWSC_MASK)) | (FMU_FCTRL_RWSC(0x1U));
    }
    BOARD_BootClockFROHF72M_InitClockModule(kClockModule_SIRC);
    BOARD_BootClockFROHF72M_InitClockModule(kClockModule_FIRC);
    BOARD_BootClockFROHF72M_InitClockModule(kClockModule_SystemClk);

    /* The flow of decreasing voltage and frequency */
    if (coreFreq > BOARD_BOOTCLOCKFROHF72M_CORE_CLOCK) {
        /* Configure Flash to support different voltage level and frequency */
        FMU0->FCTRL = (FMU0->FCTRL & ~((uint32_t)FMU_FCTRL_RWSC_MASK)) | (FMU_FCTRL_RWSC(0x1U));
    }

    BOARD_BootClockFROHF72M_InitClockModule(kClockModule_ADCClk);
    BOARD_BootClockFROHF72M_InitClockModule(kClockModule_CLKOUT);
    BOARD_BootClockFROHF72M_InitClockModule(kClockModule_CMP0Clk);
    BOARD_BootClockFROHF72M_InitClockModule(kClockModule_CTIMER0Clk);
    BOARD_BootClockFROHF72M_InitClockModule(kClockModule_CTIMER1Clk);
    BOARD_BootClockFROHF72M_InitClockModule(kClockModule_FREQME);
    BOARD_BootClockFROHF72M_InitClockModule(kClockModule_LPI2C0Clk);
    BOARD_BootClockFROHF72M_InitClockModule(kClockModule_LPSPI0Clk);
    BOARD_BootClockFROHF72M_InitClockModule(kClockModule_LPTMR0Clk);
    BOARD_BootClockFROHF72M_InitClockModule(kClockModule_LPUART0Clk);
    BOARD_BootClockFROHF72M_InitClockModule(kClockModule_LPUART1Clk);
    BOARD_BootClockFROHF72M_InitClockModule(kClockModule_LPUART2Clk);
    BOARD_BootClockFROHF72M_InitClockModule(kClockModule_LPUART3Clk);
    BOARD_BootClockFROHF72M_InitClockModule(kClockModule_SYSTICKClk);
    BOARD_BootClockFROHF72M_InitClockModule(kClockModule_TRACEClk);
    BOARD_BootClockFROHF72M_InitClockModule(kClockModule_WWDT0Clk);

    /* Set SystemCoreClock variable */
    SystemCoreClock = BOARD_BOOTCLOCKFROHF72M_CORE_CLOCK;
}
