/*
 * Copyright 2026 NXP
 * All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v17.0
processor: MCXC162
package_id: MCXC162VFT
mcu_data: ksdk2_0
processor_version: 0.0.0
pin_labels:
- {pin_num: '13', pin_signal: P2_3/TRIG_IN7/LPUART0_CTS_B/LPUART2_RXD/CT_INP13/CT0_MAT3/OPAMP0_REF_EXT_REF1_EN/ADC0_A2, label: LED_RED, identifier: LED_RED}
- {pin_num: '15', pin_signal: P2_7/TRIG_IN5/LPUART3_TXD/CT_INP19/CT1_MAT3/OPAMP0_REF_EXT_REF0_EN/VREFI/ADC0_A7, label: LED_GREEN, identifier: LED_GREEN}
- {pin_num: '3', pin_signal: P1_10/LPUART1_RTS_B/LPI2C0_SDAS/CT1_MAT0/ADC0_A8, label: LED_BLUE, identifier: LED_BLUE}
- {pin_num: '28', pin_signal: P3_14/CT_INP6/PWM0_X2, label: SW2, identifier: SW2}
- {pin_num: '25', pin_signal: P3_29/ISPMODE_N/CLKIN/CT_INP3/ADC0_A14, label: SW3, identifier: SW3}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

#include "fsl_common.h"
#include "fsl_port.h"
#include "fsl_gpio.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 *
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void)
{
    BOARD_InitDEBUG_UARTPins();
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitDEBUG_UARTPins:
- options: {callFromInitBoot: 'true', coreID: cm23_core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '40', peripheral: LPUART0, signal: RX, pin_signal: P0_2/TDO/SWO/LPUART0_RXD/LPSPI0_SCK/CT0_MAT0, slew_rate: fast, open_drain: disable, drive_strength: high,
    pull_select: down, pull_enable: disable, input_buffer: enable, invert_input: normal}
  - {pin_num: '41', peripheral: LPUART0, signal: TX, pin_signal: P0_3/TDI/LPUART0_TXD/LPSPI0_SDO/CT0_MAT1/CMP0_OUT, slew_rate: fast, open_drain: disable, drive_strength: low,
    pull_select: up, pull_enable: enable, input_buffer: enable, invert_input: normal}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitDEBUG_UARTPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitDEBUG_UARTPins(void)
{
    /* PORT0: Peripheral clock is enabled */
    CLOCK_EnableClock(kCLOCK_GatePORT0);
    /* LPUART0 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kLPUART0_RST_SHIFT_RSTn);
    /* PORT0 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kPORT0_RST_SHIFT_RSTn);

    const port_pin_config_t port0_2_pin40_config = {/* Internal pull-up/down resistor is disabled */
                                                    .pullSelect = kPORT_PullDisable,
                                                    /* Low internal pull resistor value is selected. */
                                                    .pullValueSelect = kPORT_LowPullResistor,
                                                    /* Fast slew rate is configured */
                                                    .slewRate = kPORT_FastSlewRate,
                                                    /* Passive input filter is disabled */
                                                    .passiveFilterEnable = kPORT_PassiveFilterDisable,
                                                    /* Open drain output is disabled */
                                                    .openDrainEnable = kPORT_OpenDrainDisable,
                                                    /* High drive strength is configured */
                                                    .driveStrength = kPORT_HighDriveStrength,
                                                    /* Normal drive strength is configured */
                                                    .driveStrength1 = kPORT_NormalDriveStrength,
                                                    /* Pin is configured as LPUART0_RXD */
                                                    .mux = kPORT_MuxAlt2,
                                                    /* Digital input enabled */
                                                    .inputBuffer = kPORT_InputBufferEnable,
                                                    /* Digital input is not inverted */
                                                    .invertInput = kPORT_InputNormal,
                                                    /* Pin Control Register fields [15:0] are not locked */
                                                    .lockRegister = kPORT_UnlockRegister};
    /* PORT0_2 (pin 40) is configured as LPUART0_RXD */
    PORT_SetPinConfig(PORT0, 2U, &port0_2_pin40_config);

    const port_pin_config_t port0_3_pin41_config = {/* Internal pull-up resistor is enabled */
                                                    .pullSelect = kPORT_PullUp,
                                                    /* Low internal pull resistor value is selected. */
                                                    .pullValueSelect = kPORT_LowPullResistor,
                                                    /* Fast slew rate is configured */
                                                    .slewRate = kPORT_FastSlewRate,
                                                    /* Passive input filter is disabled */
                                                    .passiveFilterEnable = kPORT_PassiveFilterDisable,
                                                    /* Open drain output is disabled */
                                                    .openDrainEnable = kPORT_OpenDrainDisable,
                                                    /* Low drive strength is configured */
                                                    .driveStrength = kPORT_LowDriveStrength,
                                                    /* Normal drive strength is configured */
                                                    .driveStrength1 = kPORT_NormalDriveStrength,
                                                    /* Pin is configured as LPUART0_TXD */
                                                    .mux = kPORT_MuxAlt2,
                                                    /* Digital input enabled */
                                                    .inputBuffer = kPORT_InputBufferEnable,
                                                    /* Digital input is not inverted */
                                                    .invertInput = kPORT_InputNormal,
                                                    /* Pin Control Register fields [15:0] are not locked */
                                                    .lockRegister = kPORT_UnlockRegister};
    /* PORT0_3 (pin 41) is configured as LPUART0_TXD */
    PORT_SetPinConfig(PORT0, 3U, &port0_3_pin41_config);
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitLEDsPins:
- options: {callFromInitBoot: 'false', coreID: cm23_core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '13', peripheral: GPIO2, signal: 'GPIO, 3', pin_signal: P2_3/TRIG_IN7/LPUART0_CTS_B/LPUART2_RXD/CT_INP13/CT0_MAT3/OPAMP0_REF_EXT_REF1_EN/ADC0_A2, direction: OUTPUT,
    gpio_init_state: 'true', slew_rate: fast, open_drain: disable, drive_strength: low, pull_select: down, pull_enable: disable, input_buffer: enable, invert_input: normal}
  - {pin_num: '15', peripheral: GPIO2, signal: 'GPIO, 7', pin_signal: P2_7/TRIG_IN5/LPUART3_TXD/CT_INP19/CT1_MAT3/OPAMP0_REF_EXT_REF0_EN/VREFI/ADC0_A7, direction: OUTPUT,
    gpio_init_state: 'true', slew_rate: fast, open_drain: disable, drive_strength: low, pull_select: down, pull_enable: disable, input_buffer: enable, invert_input: normal}
  - {pin_num: '3', peripheral: GPIO1, signal: 'GPIO, 10', pin_signal: P1_10/LPUART1_RTS_B/LPI2C0_SDAS/CT1_MAT0/ADC0_A8, direction: OUTPUT, gpio_init_state: 'true',
    slew_rate: fast, open_drain: disable, drive_strength: low, pull_select: down, pull_enable: disable, input_buffer: enable, invert_input: normal}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitLEDsPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitLEDsPins(void)
{
    /* GPIO1: Peripheral clock is enabled */
    CLOCK_EnableClock(kCLOCK_GateGPIO1);
    /* GPIO2: Peripheral clock is enabled */
    CLOCK_EnableClock(kCLOCK_GateGPIO2);
    /* PORT1: Peripheral clock is enabled */
    CLOCK_EnableClock(kCLOCK_GatePORT1);
    /* PORT2: Peripheral clock is enabled */
    CLOCK_EnableClock(kCLOCK_GatePORT2);
    /* GPIO1 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kGPIO1_RST_SHIFT_RSTn);
    /* GPIO2 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kGPIO2_RST_SHIFT_RSTn);
    /* CTIMER1 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kCTIMER1_RST_SHIFT_RSTn);
    /* PORT1 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kPORT1_RST_SHIFT_RSTn);
    /* CTIMER0 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kCTIMER0_RST_SHIFT_RSTn);
    /* PORT2 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kPORT2_RST_SHIFT_RSTn);

    const port_pin_config_t LED_BLUE = {/* Internal pull-up/down resistor is disabled */
                                        .pullSelect = kPORT_PullDisable,
                                        /* Low internal pull resistor value is selected. */
                                        .pullValueSelect = kPORT_LowPullResistor,
                                        /* Fast slew rate is configured */
                                        .slewRate = kPORT_FastSlewRate,
                                        /* Passive input filter is disabled */
                                        .passiveFilterEnable = kPORT_PassiveFilterDisable,
                                        /* Open drain output is disabled */
                                        .openDrainEnable = kPORT_OpenDrainDisable,
                                        /* Low drive strength is configured */
                                        .driveStrength = kPORT_LowDriveStrength,
                                        /* Normal drive strength is configured */
                                        .driveStrength1 = kPORT_NormalDriveStrength,
                                        /* Pin is configured as P1_10 */
                                        .mux = kPORT_MuxAlt0,
                                        /* Digital input enabled */
                                        .inputBuffer = kPORT_InputBufferEnable,
                                        /* Digital input is not inverted */
                                        .invertInput = kPORT_InputNormal,
                                        /* Pin Control Register fields [15:0] are not locked */
                                        .lockRegister = kPORT_UnlockRegister};
    /* PORT1_10 (pin 3) is configured as P1_10 */
    PORT_SetPinConfig(BOARD_INITLEDSPINS_LED_BLUE_PORT, BOARD_INITLEDSPINS_LED_BLUE_PIN, &LED_BLUE);

    const port_pin_config_t LED_RED = {/* Internal pull-up/down resistor is disabled */
                                       .pullSelect = kPORT_PullDisable,
                                       /* Low internal pull resistor value is selected. */
                                       .pullValueSelect = kPORT_LowPullResistor,
                                       /* Fast slew rate is configured */
                                       .slewRate = kPORT_FastSlewRate,
                                       /* Passive input filter is disabled */
                                       .passiveFilterEnable = kPORT_PassiveFilterDisable,
                                       /* Open drain output is disabled */
                                       .openDrainEnable = kPORT_OpenDrainDisable,
                                       /* Low drive strength is configured */
                                       .driveStrength = kPORT_LowDriveStrength,
                                       /* Normal drive strength is configured */
                                       .driveStrength1 = kPORT_NormalDriveStrength,
                                       /* Pin is configured as P2_3 */
                                       .mux = kPORT_MuxAlt0,
                                       /* Digital input enabled */
                                       .inputBuffer = kPORT_InputBufferEnable,
                                       /* Digital input is not inverted */
                                       .invertInput = kPORT_InputNormal,
                                       /* Pin Control Register fields [15:0] are not locked */
                                       .lockRegister = kPORT_UnlockRegister};
    /* PORT2_3 (pin 13) is configured as P2_3 */
    PORT_SetPinConfig(BOARD_INITLEDSPINS_LED_RED_PORT, BOARD_INITLEDSPINS_LED_RED_PIN, &LED_RED);

    const port_pin_config_t LED_GREEN = {/* Internal pull-up/down resistor is disabled */
                                         .pullSelect = kPORT_PullDisable,
                                         /* Low internal pull resistor value is selected. */
                                         .pullValueSelect = kPORT_LowPullResistor,
                                         /* Fast slew rate is configured */
                                         .slewRate = kPORT_FastSlewRate,
                                         /* Passive input filter is disabled */
                                         .passiveFilterEnable = kPORT_PassiveFilterDisable,
                                         /* Open drain output is disabled */
                                         .openDrainEnable = kPORT_OpenDrainDisable,
                                         /* Low drive strength is configured */
                                         .driveStrength = kPORT_LowDriveStrength,
                                         /* Normal drive strength is configured */
                                         .driveStrength1 = kPORT_NormalDriveStrength,
                                         /* Pin is configured as P2_7 */
                                         .mux = kPORT_MuxAlt0,
                                         /* Digital input enabled */
                                         .inputBuffer = kPORT_InputBufferEnable,
                                         /* Digital input is not inverted */
                                         .invertInput = kPORT_InputNormal,
                                         /* Pin Control Register fields [15:0] are not locked */
                                         .lockRegister = kPORT_UnlockRegister};
    /* PORT2_7 (pin 15) is configured as P2_7 */
    PORT_SetPinConfig(BOARD_INITLEDSPINS_LED_GREEN_PORT, BOARD_INITLEDSPINS_LED_GREEN_PIN, &LED_GREEN);

    gpio_pin_config_t LED_BLUE_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 1U
    };
    /* Initialize GPIO functionality on pin PIO1_10 (pin 3)  */
    GPIO_PinInit(BOARD_INITLEDSPINS_LED_BLUE_GPIO, BOARD_INITLEDSPINS_LED_BLUE_PIN, &LED_BLUE_config);

    gpio_pin_config_t LED_RED_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 1U
    };
    /* Initialize GPIO functionality on pin PIO2_3 (pin 13)  */
    GPIO_PinInit(BOARD_INITLEDSPINS_LED_RED_GPIO, BOARD_INITLEDSPINS_LED_RED_PIN, &LED_RED_config);

    gpio_pin_config_t LED_GREEN_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 1U
    };
    /* Initialize GPIO functionality on pin PIO2_7 (pin 15)  */
    GPIO_PinInit(BOARD_INITLEDSPINS_LED_GREEN_GPIO, BOARD_INITLEDSPINS_LED_GREEN_PIN, &LED_GREEN_config);
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitBUTTONsPins:
- options: {callFromInitBoot: 'false', coreID: cm23_core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '28', peripheral: GPIO3, signal: 'GPIO, 14', pin_signal: P3_14/CT_INP6/PWM0_X2, direction: INPUT, slew_rate: fast, open_drain: disable, drive_strength: low,
    pull_select: down, pull_enable: disable, input_buffer: enable, invert_input: normal}
  - {pin_num: '25', peripheral: GPIO3, signal: 'GPIO, 29', pin_signal: P3_29/ISPMODE_N/CLKIN/CT_INP3/ADC0_A14, direction: INPUT, slew_rate: fast, open_drain: disable,
    drive_strength: low, pull_select: up, pull_enable: enable, input_buffer: enable, invert_input: normal}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBUTTONsPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitBUTTONsPins(void)
{
    /* GPIO3: Peripheral clock is enabled */
    CLOCK_EnableClock(kCLOCK_GateGPIO3);
    /* PORT3: Peripheral clock is enabled */
    CLOCK_EnableClock(kCLOCK_GatePORT3);
    /* GPIO3 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kGPIO3_RST_SHIFT_RSTn);
    /* PORT3 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kPORT3_RST_SHIFT_RSTn);

    const port_pin_config_t SW2 = {/* Internal pull-up/down resistor is disabled */
                                   .pullSelect = kPORT_PullDisable,
                                   /* Low internal pull resistor value is selected. */
                                   .pullValueSelect = kPORT_LowPullResistor,
                                   /* Fast slew rate is configured */
                                   .slewRate = kPORT_FastSlewRate,
                                   /* Passive input filter is disabled */
                                   .passiveFilterEnable = kPORT_PassiveFilterDisable,
                                   /* Open drain output is disabled */
                                   .openDrainEnable = kPORT_OpenDrainDisable,
                                   /* Low drive strength is configured */
                                   .driveStrength = kPORT_LowDriveStrength,
                                   /* Normal drive strength is configured */
                                   .driveStrength1 = kPORT_NormalDriveStrength,
                                   /* Pin is configured as P3_14 */
                                   .mux = kPORT_MuxAlt0,
                                   /* Digital input enabled */
                                   .inputBuffer = kPORT_InputBufferEnable,
                                   /* Digital input is not inverted */
                                   .invertInput = kPORT_InputNormal,
                                   /* Pin Control Register fields [15:0] are not locked */
                                   .lockRegister = kPORT_UnlockRegister};
    /* PORT3_14 (pin 28) is configured as P3_14 */
    PORT_SetPinConfig(BOARD_INITBUTTONSPINS_SW2_PORT, BOARD_INITBUTTONSPINS_SW2_PIN, &SW2);

    const port_pin_config_t SW3 = {/* Internal pull-up resistor is enabled */
                                   .pullSelect = kPORT_PullUp,
                                   /* Low internal pull resistor value is selected. */
                                   .pullValueSelect = kPORT_LowPullResistor,
                                   /* Fast slew rate is configured */
                                   .slewRate = kPORT_FastSlewRate,
                                   /* Passive input filter is disabled */
                                   .passiveFilterEnable = kPORT_PassiveFilterDisable,
                                   /* Open drain output is disabled */
                                   .openDrainEnable = kPORT_OpenDrainDisable,
                                   /* Low drive strength is configured */
                                   .driveStrength = kPORT_LowDriveStrength,
                                   /* Normal drive strength is configured */
                                   .driveStrength1 = kPORT_NormalDriveStrength,
                                   /* Pin is configured as P3_29 */
                                   .mux = kPORT_MuxAlt0,
                                   /* Digital input enabled */
                                   .inputBuffer = kPORT_InputBufferEnable,
                                   /* Digital input is not inverted */
                                   .invertInput = kPORT_InputNormal,
                                   /* Pin Control Register fields [15:0] are not locked */
                                   .lockRegister = kPORT_UnlockRegister};
    /* PORT3_29 (pin 25) is configured as P3_29 */
    PORT_SetPinConfig(BOARD_INITBUTTONSPINS_SW3_PORT, BOARD_INITBUTTONSPINS_SW3_PIN, &SW3);

    gpio_pin_config_t SW2_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PIO3_14 (pin 28)  */
    GPIO_PinInit(BOARD_INITBUTTONSPINS_SW2_GPIO, BOARD_INITBUTTONSPINS_SW2_PIN, &SW2_config);

    gpio_pin_config_t SW3_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PIO3_29 (pin 25)  */
    GPIO_PinInit(BOARD_INITBUTTONSPINS_SW3_GPIO, BOARD_INITBUTTONSPINS_SW3_PIN, &SW3_config);
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitCTIMERPins:
- options: {callFromInitBoot: 'false', coreID: cm23_core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '13', peripheral: CTIMER0, signal: 'MATCH, 3', pin_signal: P2_3/TRIG_IN7/LPUART0_CTS_B/LPUART2_RXD/CT_INP13/CT0_MAT3/OPAMP0_REF_EXT_REF1_EN/ADC0_A2,
    slew_rate: fast, open_drain: disable, drive_strength: low, pull_select: down, pull_enable: disable, input_buffer: enable, invert_input: normal}
  - {pin_num: '15', peripheral: CTIMER1, signal: 'MATCH, 3', pin_signal: P2_7/TRIG_IN5/LPUART3_TXD/CT_INP19/CT1_MAT3/OPAMP0_REF_EXT_REF0_EN/VREFI/ADC0_A7, slew_rate: fast,
    open_drain: disable, drive_strength: low, pull_select: down, pull_enable: disable, input_buffer: enable, invert_input: normal}
  - {pin_num: '3', peripheral: CTIMER1, signal: 'MATCH, 0', pin_signal: P1_10/LPUART1_RTS_B/LPI2C0_SDAS/CT1_MAT0/ADC0_A8, slew_rate: fast, open_drain: disable, drive_strength: low,
    pull_select: down, pull_enable: disable, input_buffer: enable, invert_input: normal}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitCTIMERPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitCTIMERPins(void)
{
    /* PORT1: Peripheral clock is enabled */
    CLOCK_EnableClock(kCLOCK_GatePORT1);
    /* PORT2: Peripheral clock is enabled */
    CLOCK_EnableClock(kCLOCK_GatePORT2);
    /* GPIO1 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kGPIO1_RST_SHIFT_RSTn);
    /* CTIMER1 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kCTIMER1_RST_SHIFT_RSTn);
    /* PORT1 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kPORT1_RST_SHIFT_RSTn);
    /* GPIO2 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kGPIO2_RST_SHIFT_RSTn);
    /* CTIMER0 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kCTIMER0_RST_SHIFT_RSTn);
    /* PORT2 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kPORT2_RST_SHIFT_RSTn);

    const port_pin_config_t LED_BLUE = {/* Internal pull-up/down resistor is disabled */
                                        .pullSelect = kPORT_PullDisable,
                                        /* Low internal pull resistor value is selected. */
                                        .pullValueSelect = kPORT_LowPullResistor,
                                        /* Fast slew rate is configured */
                                        .slewRate = kPORT_FastSlewRate,
                                        /* Passive input filter is disabled */
                                        .passiveFilterEnable = kPORT_PassiveFilterDisable,
                                        /* Open drain output is disabled */
                                        .openDrainEnable = kPORT_OpenDrainDisable,
                                        /* Low drive strength is configured */
                                        .driveStrength = kPORT_LowDriveStrength,
                                        /* Normal drive strength is configured */
                                        .driveStrength1 = kPORT_NormalDriveStrength,
                                        /* Pin is configured as CT1_MAT0 */
                                        .mux = kPORT_MuxAlt4,
                                        /* Digital input enabled */
                                        .inputBuffer = kPORT_InputBufferEnable,
                                        /* Digital input is not inverted */
                                        .invertInput = kPORT_InputNormal,
                                        /* Pin Control Register fields [15:0] are not locked */
                                        .lockRegister = kPORT_UnlockRegister};
    /* PORT1_10 (pin 3) is configured as CT1_MAT0 */
    PORT_SetPinConfig(BOARD_INITCTIMERPINS_LED_BLUE_PORT, BOARD_INITCTIMERPINS_LED_BLUE_PIN, &LED_BLUE);

    const port_pin_config_t LED_RED = {/* Internal pull-up/down resistor is disabled */
                                       .pullSelect = kPORT_PullDisable,
                                       /* Low internal pull resistor value is selected. */
                                       .pullValueSelect = kPORT_LowPullResistor,
                                       /* Fast slew rate is configured */
                                       .slewRate = kPORT_FastSlewRate,
                                       /* Passive input filter is disabled */
                                       .passiveFilterEnable = kPORT_PassiveFilterDisable,
                                       /* Open drain output is disabled */
                                       .openDrainEnable = kPORT_OpenDrainDisable,
                                       /* Low drive strength is configured */
                                       .driveStrength = kPORT_LowDriveStrength,
                                       /* Normal drive strength is configured */
                                       .driveStrength1 = kPORT_NormalDriveStrength,
                                       /* Pin is configured as CT0_MAT3 */
                                       .mux = kPORT_MuxAlt5,
                                       /* Digital input enabled */
                                       .inputBuffer = kPORT_InputBufferEnable,
                                       /* Digital input is not inverted */
                                       .invertInput = kPORT_InputNormal,
                                       /* Pin Control Register fields [15:0] are not locked */
                                       .lockRegister = kPORT_UnlockRegister};
    /* PORT2_3 (pin 13) is configured as CT0_MAT3 */
    PORT_SetPinConfig(BOARD_INITCTIMERPINS_LED_RED_PORT, BOARD_INITCTIMERPINS_LED_RED_PIN, &LED_RED);

    const port_pin_config_t LED_GREEN = {/* Internal pull-up/down resistor is disabled */
                                         .pullSelect = kPORT_PullDisable,
                                         /* Low internal pull resistor value is selected. */
                                         .pullValueSelect = kPORT_LowPullResistor,
                                         /* Fast slew rate is configured */
                                         .slewRate = kPORT_FastSlewRate,
                                         /* Passive input filter is disabled */
                                         .passiveFilterEnable = kPORT_PassiveFilterDisable,
                                         /* Open drain output is disabled */
                                         .openDrainEnable = kPORT_OpenDrainDisable,
                                         /* Low drive strength is configured */
                                         .driveStrength = kPORT_LowDriveStrength,
                                         /* Normal drive strength is configured */
                                         .driveStrength1 = kPORT_NormalDriveStrength,
                                         /* Pin is configured as CT1_MAT3 */
                                         .mux = kPORT_MuxAlt5,
                                         /* Digital input enabled */
                                         .inputBuffer = kPORT_InputBufferEnable,
                                         /* Digital input is not inverted */
                                         .invertInput = kPORT_InputNormal,
                                         /* Pin Control Register fields [15:0] are not locked */
                                         .lockRegister = kPORT_UnlockRegister};
    /* PORT2_7 (pin 15) is configured as CT1_MAT3 */
    PORT_SetPinConfig(BOARD_INITCTIMERPINS_LED_GREEN_PORT, BOARD_INITCTIMERPINS_LED_GREEN_PIN, &LED_GREEN);
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitI2CPins:
- options: {callFromInitBoot: 'false', coreID: cm23_core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '27', peripheral: LPI2C0, signal: SCL, pin_signal: P3_27/TRIG_OUT7/LPI2C0_SCL/LPUART3_TXD/CT_INP13/PWM0_X2, slew_rate: fast, open_drain: disable, drive_strength: low,
    pull_select: down, pull_enable: disable, input_buffer: enable, invert_input: normal}
  - {pin_num: '26', peripheral: LPI2C0, signal: SDA, pin_signal: P3_28/TRIG_IN11/LPI2C0_SDA/LPUART3_RXD/CT_INP12, slew_rate: fast, open_drain: disable, drive_strength: low,
    extra_drive_strength: normal, pull_select: down, pull_enable: disable, input_buffer: enable, invert_input: normal}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitI2CPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitI2CPins(void)
{
    /* PORT3: Peripheral clock is enabled */
    CLOCK_EnableClock(kCLOCK_GatePORT3);
    /* LPI2C0 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kLPI2C0_RST_SHIFT_RSTn);
    /* PORT3 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kPORT3_RST_SHIFT_RSTn);

    const port_pin_config_t port3_27_pin27_config = {/* Internal pull-up/down resistor is disabled */
                                                     .pullSelect = kPORT_PullDisable,
                                                     /* Low internal pull resistor value is selected. */
                                                     .pullValueSelect = kPORT_LowPullResistor,
                                                     /* Fast slew rate is configured */
                                                     .slewRate = kPORT_FastSlewRate,
                                                     /* Passive input filter is disabled */
                                                     .passiveFilterEnable = kPORT_PassiveFilterDisable,
                                                     /* Open drain output is disabled */
                                                     .openDrainEnable = kPORT_OpenDrainDisable,
                                                     /* Low drive strength is configured */
                                                     .driveStrength = kPORT_LowDriveStrength,
                                                     /* Normal drive strength is configured */
                                                     .driveStrength1 = kPORT_NormalDriveStrength,
                                                     /* Pin is configured as LPI2C0_SCL */
                                                     .mux = kPORT_MuxAlt2,
                                                     /* Digital input enabled */
                                                     .inputBuffer = kPORT_InputBufferEnable,
                                                     /* Digital input is not inverted */
                                                     .invertInput = kPORT_InputNormal,
                                                     /* Pin Control Register fields [15:0] are not locked */
                                                     .lockRegister = kPORT_UnlockRegister};
    /* PORT3_27 (pin 27) is configured as LPI2C0_SCL */
    PORT_SetPinConfig(PORT3, 27U, &port3_27_pin27_config);

    const port_pin_config_t port3_28_pin26_config = {/* Internal pull-up/down resistor is disabled */
                                                     .pullSelect = kPORT_PullDisable,
                                                     /* Low internal pull resistor value is selected. */
                                                     .pullValueSelect = kPORT_LowPullResistor,
                                                     /* Fast slew rate is configured */
                                                     .slewRate = kPORT_FastSlewRate,
                                                     /* Passive input filter is disabled */
                                                     .passiveFilterEnable = kPORT_PassiveFilterDisable,
                                                     /* Open drain output is disabled */
                                                     .openDrainEnable = kPORT_OpenDrainDisable,
                                                     /* Low drive strength is configured */
                                                     .driveStrength = kPORT_LowDriveStrength,
                                                     /* Normal drive strength is configured */
                                                     .driveStrength1 = kPORT_NormalDriveStrength,
                                                     /* Pin is configured as LPI2C0_SDA */
                                                     .mux = kPORT_MuxAlt2,
                                                     /* Digital input enabled */
                                                     .inputBuffer = kPORT_InputBufferEnable,
                                                     /* Digital input is not inverted */
                                                     .invertInput = kPORT_InputNormal,
                                                     /* Pin Control Register fields [15:0] are not locked */
                                                     .lockRegister = kPORT_UnlockRegister};
    /* PORT3_28 (pin 26) is configured as LPI2C0_SDA */
    PORT_SetPinConfig(PORT3, 28U, &port3_28_pin26_config);
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitSPIPins:
- options: {callFromInitBoot: 'false', coreID: cm23_core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '33', peripheral: LPSPI0, signal: IN, pin_signal: P3_9/TRIG_IN4/LPSPI0_SDI/LPUART1_TXD/CT_INP5/PWM0_B1, slew_rate: fast, open_drain: disable, drive_strength: low,
    pull_select: down, pull_enable: disable, input_buffer: enable, invert_input: normal}
  - {pin_num: '34', peripheral: LPSPI0, signal: OUT, pin_signal: P3_8/TRIG_IN3/LPSPI0_SDO/LPUART1_RXD/CT_INP4/PWM0_A1/CLKOUT, slew_rate: fast, open_drain: disable,
    drive_strength: low, pull_select: down, pull_enable: disable, input_buffer: enable, invert_input: normal}
  - {pin_num: '31', peripheral: LPSPI0, signal: PCS0, pin_signal: P3_11/TRIG_IN6/LPSPI0_PCS0/LPUART1_CTS_B/CT1_MAT1/PWM0_B2, slew_rate: fast, open_drain: disable,
    drive_strength: low, pull_select: down, pull_enable: disable, input_buffer: enable, invert_input: normal}
  - {pin_num: '32', peripheral: LPSPI0, signal: SCK, pin_signal: P3_10/TRIG_IN5/LPSPI0_SCK/LPUART1_RTS_B/CT1_MAT0/PWM0_A2, slew_rate: fast, open_drain: disable, drive_strength: low,
    pull_select: down, pull_enable: disable, input_buffer: enable, invert_input: normal}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitSPIPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitSPIPins(void)
{
    /* PORT3: Peripheral clock is enabled */
    CLOCK_EnableClock(kCLOCK_GatePORT3);
    /* FLEXPWM0 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kFLEXPWM0_RST_SHIFT_RSTn);
    /* LPSPI0 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kLPSPI0_RST_SHIFT_RSTn);
    /* PORT3 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kPORT3_RST_SHIFT_RSTn);

    const port_pin_config_t port3_10_pin32_config = {/* Internal pull-up/down resistor is disabled */
                                                     .pullSelect = kPORT_PullDisable,
                                                     /* Low internal pull resistor value is selected. */
                                                     .pullValueSelect = kPORT_LowPullResistor,
                                                     /* Fast slew rate is configured */
                                                     .slewRate = kPORT_FastSlewRate,
                                                     /* Passive input filter is disabled */
                                                     .passiveFilterEnable = kPORT_PassiveFilterDisable,
                                                     /* Open drain output is disabled */
                                                     .openDrainEnable = kPORT_OpenDrainDisable,
                                                     /* Low drive strength is configured */
                                                     .driveStrength = kPORT_LowDriveStrength,
                                                     /* Normal drive strength is configured */
                                                     .driveStrength1 = kPORT_NormalDriveStrength,
                                                     /* Pin is configured as LPSPI0_SCK */
                                                     .mux = kPORT_MuxAlt2,
                                                     /* Digital input enabled */
                                                     .inputBuffer = kPORT_InputBufferEnable,
                                                     /* Digital input is not inverted */
                                                     .invertInput = kPORT_InputNormal,
                                                     /* Pin Control Register fields [15:0] are not locked */
                                                     .lockRegister = kPORT_UnlockRegister};
    /* PORT3_10 (pin 32) is configured as LPSPI0_SCK */
    PORT_SetPinConfig(PORT3, 10U, &port3_10_pin32_config);

    const port_pin_config_t port3_11_pin31_config = {/* Internal pull-up/down resistor is disabled */
                                                     .pullSelect = kPORT_PullDisable,
                                                     /* Low internal pull resistor value is selected. */
                                                     .pullValueSelect = kPORT_LowPullResistor,
                                                     /* Fast slew rate is configured */
                                                     .slewRate = kPORT_FastSlewRate,
                                                     /* Passive input filter is disabled */
                                                     .passiveFilterEnable = kPORT_PassiveFilterDisable,
                                                     /* Open drain output is disabled */
                                                     .openDrainEnable = kPORT_OpenDrainDisable,
                                                     /* Low drive strength is configured */
                                                     .driveStrength = kPORT_LowDriveStrength,
                                                     /* Normal drive strength is configured */
                                                     .driveStrength1 = kPORT_NormalDriveStrength,
                                                     /* Pin is configured as LPSPI0_PCS0 */
                                                     .mux = kPORT_MuxAlt2,
                                                     /* Digital input enabled */
                                                     .inputBuffer = kPORT_InputBufferEnable,
                                                     /* Digital input is not inverted */
                                                     .invertInput = kPORT_InputNormal,
                                                     /* Pin Control Register fields [15:0] are not locked */
                                                     .lockRegister = kPORT_UnlockRegister};
    /* PORT3_11 (pin 31) is configured as LPSPI0_PCS0 */
    PORT_SetPinConfig(PORT3, 11U, &port3_11_pin31_config);

    const port_pin_config_t port3_8_pin34_config = {/* Internal pull-up/down resistor is disabled */
                                                    .pullSelect = kPORT_PullDisable,
                                                    /* Low internal pull resistor value is selected. */
                                                    .pullValueSelect = kPORT_LowPullResistor,
                                                    /* Fast slew rate is configured */
                                                    .slewRate = kPORT_FastSlewRate,
                                                    /* Passive input filter is disabled */
                                                    .passiveFilterEnable = kPORT_PassiveFilterDisable,
                                                    /* Open drain output is disabled */
                                                    .openDrainEnable = kPORT_OpenDrainDisable,
                                                    /* Low drive strength is configured */
                                                    .driveStrength = kPORT_LowDriveStrength,
                                                    /* Normal drive strength is configured */
                                                    .driveStrength1 = kPORT_NormalDriveStrength,
                                                    /* Pin is configured as LPSPI0_SDO */
                                                    .mux = kPORT_MuxAlt2,
                                                    /* Digital input enabled */
                                                    .inputBuffer = kPORT_InputBufferEnable,
                                                    /* Digital input is not inverted */
                                                    .invertInput = kPORT_InputNormal,
                                                    /* Pin Control Register fields [15:0] are not locked */
                                                    .lockRegister = kPORT_UnlockRegister};
    /* PORT3_8 (pin 34) is configured as LPSPI0_SDO */
    PORT_SetPinConfig(PORT3, 8U, &port3_8_pin34_config);

    const port_pin_config_t port3_9_pin33_config = {/* Internal pull-up/down resistor is disabled */
                                                    .pullSelect = kPORT_PullDisable,
                                                    /* Low internal pull resistor value is selected. */
                                                    .pullValueSelect = kPORT_LowPullResistor,
                                                    /* Fast slew rate is configured */
                                                    .slewRate = kPORT_FastSlewRate,
                                                    /* Passive input filter is disabled */
                                                    .passiveFilterEnable = kPORT_PassiveFilterDisable,
                                                    /* Open drain output is disabled */
                                                    .openDrainEnable = kPORT_OpenDrainDisable,
                                                    /* Low drive strength is configured */
                                                    .driveStrength = kPORT_LowDriveStrength,
                                                    /* Normal drive strength is configured */
                                                    .driveStrength1 = kPORT_NormalDriveStrength,
                                                    /* Pin is configured as LPSPI0_SDI */
                                                    .mux = kPORT_MuxAlt2,
                                                    /* Digital input enabled */
                                                    .inputBuffer = kPORT_InputBufferEnable,
                                                    /* Digital input is not inverted */
                                                    .invertInput = kPORT_InputNormal,
                                                    /* Pin Control Register fields [15:0] are not locked */
                                                    .lockRegister = kPORT_UnlockRegister};
    /* PORT3_9 (pin 33) is configured as LPSPI0_SDI */
    PORT_SetPinConfig(PORT3, 9U, &port3_9_pin33_config);
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitFREQMEPins:
- options: {callFromInitBoot: 'false', coreID: cm23_core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '1', peripheral: FREQME0, signal: 'IN, 0', pin_signal: P1_8/FREQME_CLK_IN0/LPUART1_RXD/LPI2C0_SDA/CT_INP8/CT0_MAT2, slew_rate: fast, open_drain: disable,
    drive_strength: low, extra_drive_strength: normal, pull_select: down, pull_enable: disable, passive_filter: disable, input_buffer: enable, invert_input: normal}
  - {pin_num: '2', peripheral: FREQME0, signal: 'IN, 1', pin_signal: P1_9/FREQME_CLK_IN1/LPUART1_TXD/LPI2C0_SCL/CT_INP9/CT0_MAT3, slew_rate: fast, open_drain: disable,
    drive_strength: low, extra_drive_strength: normal, pull_select: down, pull_enable: disable, passive_filter: disable, input_buffer: enable, invert_input: normal}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitFREQMEPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitFREQMEPins(void)
{
    /* PORT1: Peripheral clock is enabled */
    CLOCK_EnableClock(kCLOCK_GatePORT1);
    /* FREQME peripheral is released from reset */
    RESET_ReleasePeripheralReset(kFREQME_RST_SHIFT_RSTn);
    /* PORT1 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kPORT1_RST_SHIFT_RSTn);

    const port_pin_config_t port1_8_pin1_config = {/* Internal pull-up/down resistor is disabled */
                                                   .pullSelect = kPORT_PullDisable,
                                                   /* Low internal pull resistor value is selected. */
                                                   .pullValueSelect = kPORT_LowPullResistor,
                                                   /* Fast slew rate is configured */
                                                   .slewRate = kPORT_FastSlewRate,
                                                   /* Passive input filter is disabled */
                                                   .passiveFilterEnable = kPORT_PassiveFilterDisable,
                                                   /* Open drain output is disabled */
                                                   .openDrainEnable = kPORT_OpenDrainDisable,
                                                   /* Low drive strength is configured */
                                                   .driveStrength = kPORT_LowDriveStrength,
                                                   /* Normal drive strength is configured */
                                                   .driveStrength1 = kPORT_NormalDriveStrength,
                                                   /* Pin is configured as FREQME_CLK_IN0 */
                                                   .mux = kPORT_MuxAlt1,
                                                   /* Digital input enabled */
                                                   .inputBuffer = kPORT_InputBufferEnable,
                                                   /* Digital input is not inverted */
                                                   .invertInput = kPORT_InputNormal,
                                                   /* Pin Control Register fields [15:0] are not locked */
                                                   .lockRegister = kPORT_UnlockRegister};
    /* PORT1_8 (pin 1) is configured as FREQME_CLK_IN0 */
    PORT_SetPinConfig(PORT1, 8U, &port1_8_pin1_config);

    const port_pin_config_t port1_9_pin2_config = {/* Internal pull-up/down resistor is disabled */
                                                   .pullSelect = kPORT_PullDisable,
                                                   /* Low internal pull resistor value is selected. */
                                                   .pullValueSelect = kPORT_LowPullResistor,
                                                   /* Fast slew rate is configured */
                                                   .slewRate = kPORT_FastSlewRate,
                                                   /* Passive input filter is disabled */
                                                   .passiveFilterEnable = kPORT_PassiveFilterDisable,
                                                   /* Open drain output is disabled */
                                                   .openDrainEnable = kPORT_OpenDrainDisable,
                                                   /* Low drive strength is configured */
                                                   .driveStrength = kPORT_LowDriveStrength,
                                                   /* Normal drive strength is configured */
                                                   .driveStrength1 = kPORT_NormalDriveStrength,
                                                   /* Pin is configured as FREQME_CLK_IN1 */
                                                   .mux = kPORT_MuxAlt1,
                                                   /* Digital input enabled */
                                                   .inputBuffer = kPORT_InputBufferEnable,
                                                   /* Digital input is not inverted */
                                                   .invertInput = kPORT_InputNormal,
                                                   /* Pin Control Register fields [15:0] are not locked */
                                                   .lockRegister = kPORT_UnlockRegister};
    /* PORT1_9 (pin 2) is configured as FREQME_CLK_IN1 */
    PORT_SetPinConfig(PORT1, 9U, &port1_9_pin2_config);
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitADCPins:
- options: {callFromInitBoot: 'false', coreID: cm23_core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '10', peripheral: ADC0, signal: 'A, 0', pin_signal: P2_0/TRIG_IN6/LPUART0_RXD/CT_INP16/CT0_MAT0/ADC0_A0, slew_rate: fast, open_drain: disable, drive_strength: low,
    pull_select: down, pull_enable: disable, input_buffer: disable, invert_input: normal}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitADCPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitADCPins(void)
{
    /* PORT2: Peripheral clock is enabled */
    CLOCK_EnableClock(kCLOCK_GatePORT2);
    /* ADC0 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kADC0_RST_SHIFT_RSTn);
    /* PORT2 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kPORT2_RST_SHIFT_RSTn);

    const port_pin_config_t port2_0_pin10_config = {/* Internal pull-up/down resistor is disabled */
                                                    .pullSelect = kPORT_PullDisable,
                                                    /* Low internal pull resistor value is selected. */
                                                    .pullValueSelect = kPORT_LowPullResistor,
                                                    /* Fast slew rate is configured */
                                                    .slewRate = kPORT_FastSlewRate,
                                                    /* Passive input filter is disabled */
                                                    .passiveFilterEnable = kPORT_PassiveFilterDisable,
                                                    /* Open drain output is disabled */
                                                    .openDrainEnable = kPORT_OpenDrainDisable,
                                                    /* Low drive strength is configured */
                                                    .driveStrength = kPORT_LowDriveStrength,
                                                    /* Normal drive strength is configured */
                                                    .driveStrength1 = kPORT_NormalDriveStrength,
                                                    /* Pin is configured as ADC0_A0 */
                                                    .mux = kPORT_MuxAlt0,
                                                    /* Digital input disabled; it is required for analog functions */
                                                    .inputBuffer = kPORT_InputBufferDisable,
                                                    /* Digital input is not inverted */
                                                    .invertInput = kPORT_InputNormal,
                                                    /* Pin Control Register fields [15:0] are not locked */
                                                    .lockRegister = kPORT_UnlockRegister};
    /* PORT2_0 (pin 10) is configured as ADC0_A0 */
    PORT_SetPinConfig(PORT2, 0U, &port2_0_pin10_config);
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitCMPPins:
- options: {callFromInitBoot: 'false', coreID: cm23_core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '12', peripheral: CMP0, signal: 'IN, 0P', pin_signal: P2_2/TRIG_IN6/LPUART0_RTS_B/LPUART2_TXD/CT_INP12/CT0_MAT2/ADC0_A4/CMP0_IN0, slew_rate: fast, open_drain: disable,
    drive_strength: low, pull_select: down, pull_enable: disable, input_buffer: disable, invert_input: normal}
  - {pin_num: '12', peripheral: CMP0, signal: 'IN, 0N', pin_signal: P2_2/TRIG_IN6/LPUART0_RTS_B/LPUART2_TXD/CT_INP12/CT0_MAT2/ADC0_A4/CMP0_IN0}
  - {pin_num: '12', peripheral: ADC0, signal: 'A, 4', pin_signal: P2_2/TRIG_IN6/LPUART0_RTS_B/LPUART2_TXD/CT_INP12/CT0_MAT2/ADC0_A4/CMP0_IN0}
  - {pin_num: '48', peripheral: CMP0, signal: 'IN, 1P', pin_signal: P1_3/TRIG_OUT1/LPSPI0_PCS0/LPI2C0_SCLS/CT1_MAT1/CT_INP1/ADC0_A19/CMP0_IN1, slew_rate: fast, open_drain: disable,
    drive_strength: low, pull_select: down, pull_enable: disable, input_buffer: disable, invert_input: normal}
  - {pin_num: '48', peripheral: CMP0, signal: 'IN, 1N', pin_signal: P1_3/TRIG_OUT1/LPSPI0_PCS0/LPI2C0_SCLS/CT1_MAT1/CT_INP1/ADC0_A19/CMP0_IN1}
  - {pin_num: '48', peripheral: ADC0, signal: 'A, 19', pin_signal: P1_3/TRIG_OUT1/LPSPI0_PCS0/LPI2C0_SCLS/CT1_MAT1/CT_INP1/ADC0_A19/CMP0_IN1}
  - {pin_num: '45', peripheral: CMP0, signal: 'IN, 3P', pin_signal: P1_0/TRIG_IN0/LPSPI0_SDO/LPI2C0_SDA/CT_INP4/CT0_MAT2/ADC0_A16/CMP0_IN3, slew_rate: fast, open_drain: disable,
    drive_strength: low, pull_select: down, pull_enable: disable, passive_filter: disable, input_buffer: disable, invert_input: normal}
  - {pin_num: '45', peripheral: CMP0, signal: 'IN, 3N', pin_signal: P1_0/TRIG_IN0/LPSPI0_SDO/LPI2C0_SDA/CT_INP4/CT0_MAT2/ADC0_A16/CMP0_IN3}
  - {pin_num: '45', peripheral: ADC0, signal: 'A, 16', pin_signal: P1_0/TRIG_IN0/LPSPI0_SDO/LPI2C0_SDA/CT_INP4/CT0_MAT2/ADC0_A16/CMP0_IN3}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitCMPPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitCMPPins(void)
{
    /* PORT1: Peripheral clock is enabled */
    CLOCK_EnableClock(kCLOCK_GatePORT1);
    /* PORT2: Peripheral clock is enabled */
    CLOCK_EnableClock(kCLOCK_GatePORT2);
    /* CMP0 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kCMP0_RST_SHIFT_RSTn);
    /* ADC0 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kADC0_RST_SHIFT_RSTn);
    /* PORT1 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kPORT1_RST_SHIFT_RSTn);
    /* PORT2 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kPORT2_RST_SHIFT_RSTn);

    const port_pin_config_t port1_0_pin45_config = {/* Internal pull-up/down resistor is disabled */
                                                    .pullSelect = kPORT_PullDisable,
                                                    /* Low internal pull resistor value is selected. */
                                                    .pullValueSelect = kPORT_LowPullResistor,
                                                    /* Fast slew rate is configured */
                                                    .slewRate = kPORT_FastSlewRate,
                                                    /* Passive input filter is disabled */
                                                    .passiveFilterEnable = kPORT_PassiveFilterDisable,
                                                    /* Open drain output is disabled */
                                                    .openDrainEnable = kPORT_OpenDrainDisable,
                                                    /* Low drive strength is configured */
                                                    .driveStrength = kPORT_LowDriveStrength,
                                                    /* Normal drive strength is configured */
                                                    .driveStrength1 = kPORT_NormalDriveStrength,
                                                    /* Pin is configured as CMP0_IN3, ADC0_A16 */
                                                    .mux = kPORT_MuxAlt0,
                                                    /* Digital input disabled; it is required for analog functions */
                                                    .inputBuffer = kPORT_InputBufferDisable,
                                                    /* Digital input is not inverted */
                                                    .invertInput = kPORT_InputNormal,
                                                    /* Pin Control Register fields [15:0] are not locked */
                                                    .lockRegister = kPORT_UnlockRegister};
    /* PORT1_0 (pin 45) is configured as CMP0_IN3, ADC0_A16 */
    PORT_SetPinConfig(PORT1, 0U, &port1_0_pin45_config);

    const port_pin_config_t port1_3_pin48_config = {/* Internal pull-up/down resistor is disabled */
                                                    .pullSelect = kPORT_PullDisable,
                                                    /* Low internal pull resistor value is selected. */
                                                    .pullValueSelect = kPORT_LowPullResistor,
                                                    /* Fast slew rate is configured */
                                                    .slewRate = kPORT_FastSlewRate,
                                                    /* Passive input filter is disabled */
                                                    .passiveFilterEnable = kPORT_PassiveFilterDisable,
                                                    /* Open drain output is disabled */
                                                    .openDrainEnable = kPORT_OpenDrainDisable,
                                                    /* Low drive strength is configured */
                                                    .driveStrength = kPORT_LowDriveStrength,
                                                    /* Normal drive strength is configured */
                                                    .driveStrength1 = kPORT_NormalDriveStrength,
                                                    /* Pin is configured as CMP0_IN1, ADC0_A19 */
                                                    .mux = kPORT_MuxAlt0,
                                                    /* Digital input disabled; it is required for analog functions */
                                                    .inputBuffer = kPORT_InputBufferDisable,
                                                    /* Digital input is not inverted */
                                                    .invertInput = kPORT_InputNormal,
                                                    /* Pin Control Register fields [15:0] are not locked */
                                                    .lockRegister = kPORT_UnlockRegister};
    /* PORT1_3 (pin 48) is configured as CMP0_IN1, ADC0_A19 */
    PORT_SetPinConfig(PORT1, 3U, &port1_3_pin48_config);

    const port_pin_config_t port2_2_pin12_config = {/* Internal pull-up/down resistor is disabled */
                                                    .pullSelect = kPORT_PullDisable,
                                                    /* Low internal pull resistor value is selected. */
                                                    .pullValueSelect = kPORT_LowPullResistor,
                                                    /* Fast slew rate is configured */
                                                    .slewRate = kPORT_FastSlewRate,
                                                    /* Passive input filter is disabled */
                                                    .passiveFilterEnable = kPORT_PassiveFilterDisable,
                                                    /* Open drain output is disabled */
                                                    .openDrainEnable = kPORT_OpenDrainDisable,
                                                    /* Low drive strength is configured */
                                                    .driveStrength = kPORT_LowDriveStrength,
                                                    /* Normal drive strength is configured */
                                                    .driveStrength1 = kPORT_NormalDriveStrength,
                                                    /* Pin is configured as CMP0_IN0, ADC0_A4 */
                                                    .mux = kPORT_MuxAlt0,
                                                    /* Digital input disabled; it is required for analog functions */
                                                    .inputBuffer = kPORT_InputBufferDisable,
                                                    /* Digital input is not inverted */
                                                    .invertInput = kPORT_InputNormal,
                                                    /* Pin Control Register fields [15:0] are not locked */
                                                    .lockRegister = kPORT_UnlockRegister};
    /* PORT2_2 (pin 12) is configured as CMP0_IN0, ADC0_A4 */
    PORT_SetPinConfig(PORT2, 2U, &port2_2_pin12_config);
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPWMPins:
- options: {callFromInitBoot: 'false', coreID: cm23_core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '36', peripheral: FLEXPWM0, signal: 'A, 0', pin_signal: P3_0/TRIG_IN0/LPI2C0_SCL/CT_INP16/PWM0_A0, slew_rate: fast, open_drain: disable, drive_strength: low,
    extra_drive_strength: normal, pull_select: down, pull_enable: disable, passive_filter: disable, input_buffer: enable, invert_input: normal}
  - {pin_num: '34', peripheral: FLEXPWM0, signal: 'A, 1', pin_signal: P3_8/TRIG_IN3/LPSPI0_SDO/LPUART1_RXD/CT_INP4/PWM0_A1/CLKOUT, slew_rate: fast, open_drain: disable,
    drive_strength: low, pull_select: down, pull_enable: disable, input_buffer: enable, invert_input: normal}
  - {pin_num: '32', peripheral: FLEXPWM0, signal: 'A, 2', pin_signal: P3_10/TRIG_IN5/LPSPI0_SCK/LPUART1_RTS_B/CT1_MAT0/PWM0_A2, slew_rate: fast, open_drain: disable,
    drive_strength: low, pull_select: down, pull_enable: disable, input_buffer: enable, invert_input: normal}
  - {pin_num: '35', peripheral: FLEXPWM0, signal: 'B, 0', pin_signal: P3_1/TRIG_IN1/LPI2C0_SDA/CT_INP17/PWM0_B0/FREQME_CLK_OUT0, slew_rate: fast, open_drain: disable,
    drive_strength: low, extra_drive_strength: normal, pull_select: down, pull_enable: disable, passive_filter: disable, input_buffer: enable, invert_input: normal}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPWMPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitPWMPins(void)
{
    /* PORT3: Peripheral clock is enabled */
    CLOCK_EnableClock(kCLOCK_GatePORT3);
    /* FLEXPWM0 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kFLEXPWM0_RST_SHIFT_RSTn);
    /* PORT3 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kPORT3_RST_SHIFT_RSTn);
    /* LPSPI0 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kLPSPI0_RST_SHIFT_RSTn);

    const port_pin_config_t port3_0_pin36_config = {/* Internal pull-up/down resistor is disabled */
                                                    .pullSelect = kPORT_PullDisable,
                                                    /* Low internal pull resistor value is selected. */
                                                    .pullValueSelect = kPORT_LowPullResistor,
                                                    /* Fast slew rate is configured */
                                                    .slewRate = kPORT_FastSlewRate,
                                                    /* Passive input filter is disabled */
                                                    .passiveFilterEnable = kPORT_PassiveFilterDisable,
                                                    /* Open drain output is disabled */
                                                    .openDrainEnable = kPORT_OpenDrainDisable,
                                                    /* Low drive strength is configured */
                                                    .driveStrength = kPORT_LowDriveStrength,
                                                    /* Normal drive strength is configured */
                                                    .driveStrength1 = kPORT_NormalDriveStrength,
                                                    /* Pin is configured as PWM0_A0 */
                                                    .mux = kPORT_MuxAlt5,
                                                    /* Digital input enabled */
                                                    .inputBuffer = kPORT_InputBufferEnable,
                                                    /* Digital input is not inverted */
                                                    .invertInput = kPORT_InputNormal,
                                                    /* Pin Control Register fields [15:0] are not locked */
                                                    .lockRegister = kPORT_UnlockRegister};
    /* PORT3_0 (pin 36) is configured as PWM0_A0 */
    PORT_SetPinConfig(PORT3, 0U, &port3_0_pin36_config);

    const port_pin_config_t port3_1_pin35_config = {/* Internal pull-up/down resistor is disabled */
                                                    .pullSelect = kPORT_PullDisable,
                                                    /* Low internal pull resistor value is selected. */
                                                    .pullValueSelect = kPORT_LowPullResistor,
                                                    /* Fast slew rate is configured */
                                                    .slewRate = kPORT_FastSlewRate,
                                                    /* Passive input filter is disabled */
                                                    .passiveFilterEnable = kPORT_PassiveFilterDisable,
                                                    /* Open drain output is disabled */
                                                    .openDrainEnable = kPORT_OpenDrainDisable,
                                                    /* Low drive strength is configured */
                                                    .driveStrength = kPORT_LowDriveStrength,
                                                    /* Normal drive strength is configured */
                                                    .driveStrength1 = kPORT_NormalDriveStrength,
                                                    /* Pin is configured as PWM0_B0 */
                                                    .mux = kPORT_MuxAlt5,
                                                    /* Digital input enabled */
                                                    .inputBuffer = kPORT_InputBufferEnable,
                                                    /* Digital input is not inverted */
                                                    .invertInput = kPORT_InputNormal,
                                                    /* Pin Control Register fields [15:0] are not locked */
                                                    .lockRegister = kPORT_UnlockRegister};
    /* PORT3_1 (pin 35) is configured as PWM0_B0 */
    PORT_SetPinConfig(PORT3, 1U, &port3_1_pin35_config);

    const port_pin_config_t port3_10_pin32_config = {/* Internal pull-up/down resistor is disabled */
                                                     .pullSelect = kPORT_PullDisable,
                                                     /* Low internal pull resistor value is selected. */
                                                     .pullValueSelect = kPORT_LowPullResistor,
                                                     /* Fast slew rate is configured */
                                                     .slewRate = kPORT_FastSlewRate,
                                                     /* Passive input filter is disabled */
                                                     .passiveFilterEnable = kPORT_PassiveFilterDisable,
                                                     /* Open drain output is disabled */
                                                     .openDrainEnable = kPORT_OpenDrainDisable,
                                                     /* Low drive strength is configured */
                                                     .driveStrength = kPORT_LowDriveStrength,
                                                     /* Normal drive strength is configured */
                                                     .driveStrength1 = kPORT_NormalDriveStrength,
                                                     /* Pin is configured as PWM0_A2 */
                                                     .mux = kPORT_MuxAlt5,
                                                     /* Digital input enabled */
                                                     .inputBuffer = kPORT_InputBufferEnable,
                                                     /* Digital input is not inverted */
                                                     .invertInput = kPORT_InputNormal,
                                                     /* Pin Control Register fields [15:0] are not locked */
                                                     .lockRegister = kPORT_UnlockRegister};
    /* PORT3_10 (pin 32) is configured as PWM0_A2 */
    PORT_SetPinConfig(PORT3, 10U, &port3_10_pin32_config);

    const port_pin_config_t port3_8_pin34_config = {/* Internal pull-up/down resistor is disabled */
                                                    .pullSelect = kPORT_PullDisable,
                                                    /* Low internal pull resistor value is selected. */
                                                    .pullValueSelect = kPORT_LowPullResistor,
                                                    /* Fast slew rate is configured */
                                                    .slewRate = kPORT_FastSlewRate,
                                                    /* Passive input filter is disabled */
                                                    .passiveFilterEnable = kPORT_PassiveFilterDisable,
                                                    /* Open drain output is disabled */
                                                    .openDrainEnable = kPORT_OpenDrainDisable,
                                                    /* Low drive strength is configured */
                                                    .driveStrength = kPORT_LowDriveStrength,
                                                    /* Normal drive strength is configured */
                                                    .driveStrength1 = kPORT_NormalDriveStrength,
                                                    /* Pin is configured as PWM0_A1 */
                                                    .mux = kPORT_MuxAlt5,
                                                    /* Digital input enabled */
                                                    .inputBuffer = kPORT_InputBufferEnable,
                                                    /* Digital input is not inverted */
                                                    .invertInput = kPORT_InputNormal,
                                                    /* Pin Control Register fields [15:0] are not locked */
                                                    .lockRegister = kPORT_UnlockRegister};
    /* PORT3_8 (pin 34) is configured as PWM0_A1 */
    PORT_SetPinConfig(PORT3, 8U, &port3_8_pin34_config);
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitOPAMPPins:
- options: {callFromInitBoot: 'false', coreID: cm23_core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '17', peripheral: OPAMP0, signal: 'op_inn, 0', pin_signal: P2_13/TRIG_IN8/LPSPI0_SDO/LPUART1_TXD/CT0_MAT1/OPAMP0_INN, slew_rate: fast, open_drain: disable,
    drive_strength: low, pull_select: down, pull_enable: disable, input_buffer: disable, invert_input: normal}
  - {pin_num: '16', peripheral: OPAMP0, signal: 'op_inp, 0', pin_signal: P2_12/LPSPI0_SCK/LPUART1_RXD/CT0_MAT0/ADC0_A5/OPAMP0_INP0, slew_rate: fast, open_drain: disable,
    drive_strength: low, pull_select: down, pull_enable: disable, input_buffer: disable, invert_input: normal}
  - {pin_num: '16', peripheral: ADC0, signal: 'A, 5', pin_signal: P2_12/LPSPI0_SCK/LPUART1_RXD/CT0_MAT0/ADC0_A5/OPAMP0_INP0}
  - {pin_num: '18', peripheral: OPAMP0, signal: OUT, pin_signal: P2_16/LPSPI0_SDI/LPUART1_RTS_B/CT0_MAT2/OPAMP0_OUT_EN/ADC0_A6/CMP0_IN4P, slew_rate: fast, open_drain: disable,
    drive_strength: low, pull_select: down, pull_enable: disable, input_buffer: enable, invert_input: normal}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitOPAMPPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitOPAMPPins(void)
{
    /* PORT2: Peripheral clock is enabled */
    CLOCK_EnableClock(kCLOCK_GatePORT2);
    /* OPAMP0 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kOPAMP0_RST_SHIFT_RSTn);
    /* ADC0 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kADC0_RST_SHIFT_RSTn);
    /* PORT2 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kPORT2_RST_SHIFT_RSTn);

    const port_pin_config_t port2_12_pin16_config = {/* Internal pull-up/down resistor is disabled */
                                                     .pullSelect = kPORT_PullDisable,
                                                     /* Low internal pull resistor value is selected. */
                                                     .pullValueSelect = kPORT_LowPullResistor,
                                                     /* Fast slew rate is configured */
                                                     .slewRate = kPORT_FastSlewRate,
                                                     /* Passive input filter is disabled */
                                                     .passiveFilterEnable = kPORT_PassiveFilterDisable,
                                                     /* Open drain output is disabled */
                                                     .openDrainEnable = kPORT_OpenDrainDisable,
                                                     /* Low drive strength is configured */
                                                     .driveStrength = kPORT_LowDriveStrength,
                                                     /* Normal drive strength is configured */
                                                     .driveStrength1 = kPORT_NormalDriveStrength,
                                                     /* Pin is configured as OPAMP0_INP0, ADC0_A5 */
                                                     .mux = kPORT_MuxAlt0,
                                                     /* Digital input disabled; it is required for analog functions */
                                                     .inputBuffer = kPORT_InputBufferDisable,
                                                     /* Digital input is not inverted */
                                                     .invertInput = kPORT_InputNormal,
                                                     /* Pin Control Register fields [15:0] are not locked */
                                                     .lockRegister = kPORT_UnlockRegister};
    /* PORT2_12 (pin 16) is configured as OPAMP0_INP0, ADC0_A5 */
    PORT_SetPinConfig(PORT2, 12U, &port2_12_pin16_config);

    const port_pin_config_t port2_13_pin17_config = {/* Internal pull-up/down resistor is disabled */
                                                     .pullSelect = kPORT_PullDisable,
                                                     /* Low internal pull resistor value is selected. */
                                                     .pullValueSelect = kPORT_LowPullResistor,
                                                     /* Fast slew rate is configured */
                                                     .slewRate = kPORT_FastSlewRate,
                                                     /* Passive input filter is disabled */
                                                     .passiveFilterEnable = kPORT_PassiveFilterDisable,
                                                     /* Open drain output is disabled */
                                                     .openDrainEnable = kPORT_OpenDrainDisable,
                                                     /* Low drive strength is configured */
                                                     .driveStrength = kPORT_LowDriveStrength,
                                                     /* Normal drive strength is configured */
                                                     .driveStrength1 = kPORT_NormalDriveStrength,
                                                     /* Pin is configured as OPAMP0_INN */
                                                     .mux = kPORT_MuxAlt0,
                                                     /* Digital input disabled; it is required for analog functions */
                                                     .inputBuffer = kPORT_InputBufferDisable,
                                                     /* Digital input is not inverted */
                                                     .invertInput = kPORT_InputNormal,
                                                     /* Pin Control Register fields [15:0] are not locked */
                                                     .lockRegister = kPORT_UnlockRegister};
    /* PORT2_13 (pin 17) is configured as OPAMP0_INN */
    PORT_SetPinConfig(PORT2, 13U, &port2_13_pin17_config);

    const port_pin_config_t port2_16_pin18_config = {/* Internal pull-up/down resistor is disabled */
                                                     .pullSelect = kPORT_PullDisable,
                                                     /* Low internal pull resistor value is selected. */
                                                     .pullValueSelect = kPORT_LowPullResistor,
                                                     /* Fast slew rate is configured */
                                                     .slewRate = kPORT_FastSlewRate,
                                                     /* Passive input filter is disabled */
                                                     .passiveFilterEnable = kPORT_PassiveFilterDisable,
                                                     /* Open drain output is disabled */
                                                     .openDrainEnable = kPORT_OpenDrainDisable,
                                                     /* Low drive strength is configured */
                                                     .driveStrength = kPORT_LowDriveStrength,
                                                     /* Normal drive strength is configured */
                                                     .driveStrength1 = kPORT_NormalDriveStrength,
                                                     /* Pin is configured as OPAMP0_OUT_EN */
                                                     .mux = kPORT_MuxAlt9,
                                                     /* Digital input enabled */
                                                     .inputBuffer = kPORT_InputBufferEnable,
                                                     /* Digital input is not inverted */
                                                     .invertInput = kPORT_InputNormal,
                                                     /* Pin Control Register fields [15:0] are not locked */
                                                     .lockRegister = kPORT_UnlockRegister};
    /* PORT2_16 (pin 18) is configured as OPAMP0_OUT_EN */
    PORT_SetPinConfig(PORT2, 16U, &port2_16_pin18_config);
}
/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
